// packages/cli/src/plugins/posthog/posthog.plugin.ts
//
// The product-observability plugin (PLAN.md section 2/4, ARCHITECTURE.md
// section 20 — the second plugin, proving the ObservabilityPlugin interface
// and multi-plugin composition actually generalize beyond OTel).
//
// Deliberately narrow scope for v0, mirroring the OTel plugin's own
// restraint: captures one event per tool call ("mcp tool called") with
// name/duration/success/error properties, using posthog-node's built-in
// batching + shutdown() flush. No feature flags, no session recording, no
// group analytics — those are real posthog-node capabilities but out of
// scope until there's a concrete need (same "don't guess, don't
// over-build" principle as the OTel plugin's OTLP-exporter-only choice).
//
// stdio-safety note (unlike the OTel plugin, this one has NO equivalent of
// spike/FINDINGS.md's ConsoleSpanExporter finding to encode): posthog-node
// only ever writes to console.error/console.warn internally (verified by
// inspecting its published dist/ directly), which go to stderr in Node —
// never stdout. So there's no exporter-choice landmine here the way there
// was for OTel. Still worth stating explicitly since it's a hard invariant
// this whole project depends on (ARCHITECTURE.md section 7/8's spirit
// applied to a dependency's own I/O behavior, not just our generated code).

import type {
  ObservabilityPlugin,
  PluginConfigField,
  ResolvedPluginConfig,
  TemplateContribution,
} from "../plugin.interface.js";

const CONFIG_SCHEMA: PluginConfigField[] = [
  {
    key: "apiHost",
    prompt: "PostHog API host",
    default: "https://us.i.posthog.com",
    required: true,
  },
];

function generateInstrumentationFile(config: ResolvedPluginConfig): string {
  return `// GENERATED by mcpforge (posthog plugin) — vendored instrumentation helper.
// Captures one "mcp tool called" event per tool call: name, duration,
// success/error, and (if provided) the arguments. posthog-node batches
// events internally and only ever logs to console.error/console.warn
// (stderr) on its own — never stdout, so this is safe alongside stdio MCP
// transport the same way the OTel plugin's OTLPTraceExporter is (see
// spike/FINDINGS.md for why that distinction matters at all).

import { PostHog } from "posthog-node";

const API_KEY = process.env.POSTHOG_API_KEY;
if (!API_KEY) {
  console.error(
    "Missing required environment variable POSTHOG_API_KEY. " +
      "Set it to your PostHog project API key to enable product observability, " +
      "or remove the posthog plugin at generation time if you don't want it."
  );
  process.exit(1);
}

const API_HOST = process.env.POSTHOG_API_HOST || ${JSON.stringify(config.apiHost)};

const posthog = new PostHog(API_KEY, { host: API_HOST });

// Flush on exit — posthog-node batches events internally, so an unflushed
// batch is lost on process exit otherwise (same class of bug as OTel's
// BatchSpanProcessor finding in spike/FINDINGS.md, different SDK).
process.on("SIGINT", () => posthog.shutdown().finally(() => process.exit(0)));
process.on("SIGTERM", () => posthog.shutdown().finally(() => process.exit(0)));

/**
 * Wraps an MCP tool handler to capture a PostHog product-analytics event
 * per call. Every generated tool is wired through this — no per-tool
 * custom instrumentation code needed, mirroring the OTel plugin's wrapTool.
 */
export function wrapPostHogTool<T extends (args: any) => Promise<unknown>>(toolName: string, handler: T): T {
  return (async (args: any) => {
    const startedAt = Date.now();
    // A fixed distinct_id is a deliberate v0 simplification: this server
    // has no notion of an end user identity (the MCP client is the
    // caller, not a logged-in human) — every event is attributed to the
    // server itself. Revisit if/when per-caller identity becomes
    // available (e.g. via MCP client info) and is worth surfacing.
    const distinctId = "mcp-server";
    try {
      const result = await handler(args);
      posthog.capture({
        distinctId,
        event: "mcp tool called",
        properties: {
          tool_name: toolName,
          duration_ms: Date.now() - startedAt,
          success: true,
        },
      });
      return result;
    } catch (err) {
      posthog.capture({
        distinctId,
        event: "mcp tool called",
        properties: {
          tool_name: toolName,
          duration_ms: Date.now() - startedAt,
          success: false,
          error_message: String(err),
        },
      });
      throw err;
    }
  }) as T;
}
`;
}

export const posthogPlugin: ObservabilityPlugin = {
  id: "posthog",
  name: "PostHog (product observability)",
  configSchema: CONFIG_SCHEMA,

  getTemplateContributions(config: ResolvedPluginConfig): TemplateContribution[] {
    return [
      {
        path: "src/instrumentation/posthog.ts",
        content: generateInstrumentationFile(config),
      },
    ];
  },

  getDependencies(): Record<string, string> {
    return {
      "posthog-node": "^5.0.0",
    };
  },

  getServerWiring() {
    return {
      importStatement: `import { wrapPostHogTool } from "./instrumentation/posthog.js";`,
      wrapFunctionName: "wrapPostHogTool",
    };
  },
};
