// packages/cli/src/emit/emit-project-files.ts
//
// Emits package.json + tsconfig.json for the generated v2 MCP server project.
// v2 dependency set (@modelcontextprotocol/server + /node, zod v4) — NOT the
// v1 @modelcontextprotocol/sdk, and none of openapi-mcp-generator's v1
// runtime deps (hono/fetch-to-node/uuid). Versions match the set validated
// in spikes/021-sdk-v2-streamable-http.

import type { Transport } from "./emit-server.js";

const SDK_SERVER_VERSION = "^2.0.0";
const SDK_NODE_VERSION = "^2.0.0";
const ZOD_VERSION = "^4.2.0";
const JOSE_VERSION = "^6.2.0";

export function emitPackageJson(
  serverName: string,
  transport: Transport,
  extraDependencies: Record<string, string> = {},
  registryName?: string,
  needsAuth = false
): string {
  const dependencies: Record<string, string> = {
    "@modelcontextprotocol/server": SDK_SERVER_VERSION,
    zod: ZOD_VERSION,
    ...extraDependencies,
  };
  // The node adapter is only needed for the HTTP transport's host/origin
  // validation + toNodeHandler; stdio uses @modelcontextprotocol/server/stdio.
  if (transport === "streamable-http") {
    dependencies["@modelcontextprotocol/node"] = SDK_NODE_VERSION;
  }
  // MCPFO-22: jose is the zero-dependency JOSE/JWT library used by
  // src/auth.ts for remote-JWKS bearer token verification.
  if (needsAuth) {
    dependencies["jose"] = JOSE_VERSION;
  }

  const startScript =
    transport === "streamable-http" ? "node dist/index.js" : "node dist/index.js";

  const pkg: Record<string, unknown> = {
    name: serverName,
    version: "1.0.0",
    private: true,
    type: "module",
    main: "dist/index.js",
    // mcpName is the official MCP Registry's npm package-ownership proof: it
    // MUST equal the server.json `name`. Only emitted when a registry name is
    // configured (MCPFO-25).
    ...(registryName ? { mcpName: registryName } : {}),
    scripts: {
      build: "tsc -p tsconfig.json",
      start: startScript,
    },
    engines: { node: ">=20.0.0" },
    dependencies,
    devDependencies: {
      "@types/node": "^22.10.5",
      typescript: "^5.7.3",
    },
  };
  return JSON.stringify(pkg, null, 2) + "\n";
}

export interface ServerJsonOptions {
  serverName: string;
  description: string;
  transport: Transport;
  /** Reverse-DNS registry name, e.g. "io.github.acme/petstore". Defaults to a
   *  documented placeholder the author must customize before publishing. */
  registryName?: string;
  /** npm package identifier to publish as; defaults to the server name. */
  npmIdentifier?: string;
  version?: string;
}

/**
 * Emits a server.json for the official MCP Registry (MCPFO-25). Schema verified
 * against the live registry 2026-09-03 (2025-12-11). Feeds GitHub/VS Code,
 * PulseMCP, Glama and Docker's community registry from a single upstream.
 * Publish with: `mcp-publisher login github && mcp-publisher publish`.
 */
export function emitServerJson(opts: ServerJsonOptions): string {
  const registryName = opts.registryName ?? `io.github.OWNER/${opts.serverName}`;
  const version = opts.version ?? "1.0.0";
  const identifier = opts.npmIdentifier ?? opts.serverName;
  const server = {
    $schema: "https://static.modelcontextprotocol.io/schemas/2025-12-11/server.schema.json",
    name: registryName,
    description: opts.description || `${opts.serverName} — MCP server generated by mcpforge`,
    version,
    packages: [
      {
        registryType: "npm",
        registryBaseUrl: "https://registry.npmjs.org",
        identifier,
        version,
        transport: { type: opts.transport },
        environmentVariables: [
          {
            name: "MCPFORGE_BASE_URL",
            description: "Base URL of the upstream HTTP API this server proxies.",
            isRequired: true,
          },
          {
            name: "MCPFORGE_AUTH_TOKEN",
            description: "Bearer token for the upstream API, if it requires auth.",
            isRequired: false,
            isSecret: true,
          },
        ],
      },
    ],
  };
  return JSON.stringify(server, null, 2) + "\n";
}

export function emitTsconfig(): string {
  const tsconfig = {
    compilerOptions: {
      // v2's published .d.mts references Buffer; TS >=6 no longer auto-includes
      // @types/*, so "types": ["node"] is required (v2 README).
      types: ["node"],
      target: "ES2022",
      module: "NodeNext",
      moduleResolution: "NodeNext",
      outDir: "dist",
      rootDir: "src",
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      declaration: false,
    },
    include: ["src/**/*.ts"],
  };
  return JSON.stringify(tsconfig, null, 2) + "\n";
}
