// packages/cli/src/emit/emit-sandbox.ts
//
// Emits the `execute_code` MCP tool (MCPFO-30) for SDK code mode
// (ARCHITECTURE.md sections 43/44): a single tool that runs model-written
// TypeScript against the typed client (emit-client.ts, MCPFO-29) inside a
// sandboxed Deno subprocess, instead of one MCP tool per operation.
//
// Design validated against a real local proof-of-concept before writing this
// file (Deno 2.9.6, confirmed via `deno run`): `--allow-net=<api-host-only>`,
// `--allow-read=<generated-project-dist-dir-only>`, a minimal `--allow-env`
// allowlist (KLARIDIAN_BASE_URL + KLARIDIAN_AUTH_TOKEN — the exact two vars
// client.ts reads), and no `--allow-write` at all block every exfiltration
// vector tried (cross-host fetch, arbitrary file write, arbitrary file read)
// while the legitimate call path (import the generated client, call an
// operation, get real data back) works unmodified. Model code is piped over
// stdin as a Deno program (`deno run - `) with cwd set to the compiled
// client's directory, so relative `import { x } from "./client.js"` resolves
// without writing a temp file to disk per invocation.

/**
 * Extracts the `host` or `host:port` portion from an absolute base URL, in
 * the shape Deno's `--allow-net` expects (no scheme, no path). Throws if the
 * URL isn't absolute — code mode requires a concrete API host to scope the
 * sandbox's network permission to; an unresolved/relative base URL (see
 * `resolveBaseUrlWarning` in emit-server.ts) can't be sandboxed safely.
 */
export function extractApiHost(baseUrl: string): string {
  let parsed: URL;
  try {
    parsed = new URL(baseUrl);
  } catch {
    throw new Error(`Cannot derive a sandbox network permission from base URL "${baseUrl}" — it is not a valid absolute URL.`);
  }
  return parsed.port ? `${parsed.hostname}:${parsed.port}` : parsed.hostname;
}

/**
 * Deno permission flags for the execute_code sandbox. Kept as a small pure
 * function (not inlined at the call site) so MCPFO-30's real spawn wiring
 * and this file's tests exercise identical flag-construction logic.
 *
 * `apiHost` should be `host` or `host:port` (no scheme) — Deno's `--allow-net`
 * matches on that shape. `distDir` is the absolute path to the generated
 * project's compiled output directory (where client.js lives); read access
 * is scoped to exactly that directory, never the whole filesystem.
 */
export function buildDenoPermissionFlags(opts: { apiHost: string; distDir: string }): string[] {
  return [
    `--allow-net=${opts.apiHost}`,
    `--allow-read=${opts.distDir}`,
    // The generated client (client.ts, MCPFO-29) reads exactly these two
    // env vars and no others — see emit-client.ts's emitFunctionBody. Any
    // third-party secret in the parent process's environment stays
    // invisible to model-written code even if it tries `Deno.env.toObject()`.
    `--allow-env=KLARIDIAN_BASE_URL,KLARIDIAN_AUTH_TOKEN`,
    // Deliberately no --allow-write, no --allow-run, no --allow-ffi, no
    // --allow-sys: model-written code has no legitimate need for any of
    // them, and omitting them is the actual sandboxing (Deno denies by
    // default; only what's explicitly listed here is reachable).
  ];
}

/**
 * Emits `src/sandbox-runner.ts` — the generated project's own wrapper around
 * `deno run`, invoked by the execute_code MCP tool handler. Kept as a
 * separate vendored file (not inlined string-building in the tool handler)
 * so it can itself be unit- and integration-tested independently, and so a
 * generated project's author can read exactly what runs model code, per the
 * project's "fail loudly, don't guess" + auditability principles (section 7).
 */
export function emitSandboxRunner(): string {
  return `// Generated by klaridian — SDK code mode sandbox runner (MCPFO-30).
// Spawns a Deno subprocess with a minimal, explicit permission set to run
// model-written TypeScript against the typed API client (./client.js).
// Deno is required at runtime; it is NOT vendored (a separate binary, not
// source) — see ARCHITECTURE.md section 43 point 3 for why this is an
// accepted, documented deviation from the project's vendored-source rule.
// Do not edit directly; regenerate with \\\`klaridian generate\\\`.

import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export interface SandboxResult {
  ok: boolean;
  stdout: string;
  stderr: string;
}

/**
 * Runs \\\`code\\\` (a TypeScript/JavaScript module body written by the model,
 * expected to \\\`import\\\` from "./client.js" and \\\`console.log\\\` its result) in
 * an isolated Deno subprocess. Read access is scoped to this file's own
 * directory (where the compiled client lives); network access is scoped to
 * the configured API host only; only the two env vars the client actually
 * needs are passed through. Returns captured stdout/stderr rather than
 * throwing, so the MCP tool handler can report execution failures back to
 * the model as a normal (non-protocol-error) tool result.
 */
export async function runInSandbox(code: string, apiHost: string): Promise<SandboxResult> {
  return new Promise((resolve) => {
    const args = [
      "run",
      \`--allow-net=\${apiHost}\`,
      \`--allow-read=\${__dirname}\`,
      "--allow-env=KLARIDIAN_BASE_URL,KLARIDIAN_AUTH_TOKEN",
      "-", // read the program from stdin
    ];
    const child = spawn("deno", args, {
      cwd: __dirname,
      env: {
        // PATH is required so the OS can locate the "deno" binary at all —
        // spawn() does not fall back to the parent's PATH when a partial
        // env object is supplied. Only PATH plus the two vars the client
        // reads are passed through; nothing else from this process's
        // environment (secrets, other API keys, etc.) reaches the sandbox.
        PATH: process.env.PATH ?? "",
        KLARIDIAN_BASE_URL: process.env.KLARIDIAN_BASE_URL ?? "",
        KLARIDIAN_AUTH_TOKEN: process.env.KLARIDIAN_AUTH_TOKEN ?? "",
      },
      stdio: ["pipe", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (c: Buffer) => { stdout += c.toString("utf-8"); });
    child.stderr.on("data", (c: Buffer) => { stderr += c.toString("utf-8"); });
    child.on("error", (err) => {
      // Deno binary not found, or failed to spawn at all.
      resolve({ ok: false, stdout, stderr: stderr + \`\\\\nSandbox spawn error: \${err.message}\` });
    });
    child.on("close", (exitCode) => {
      resolve({ ok: exitCode === 0, stdout, stderr });
    });

    child.stdin.write(code);
    child.stdin.end();
  });
}
`;
}

/**
 * Emits the `execute_code` MCP tool registration block, matching the same
 * `server.registerTool(...)` shape emit-tool.ts already uses for 1:1 tools
 * — SDK code mode replaces N per-operation tool blocks with exactly this one.
 */
export function emitExecuteCodeToolBlock(apiHost: string): string {
  return `  server.registerTool(
    "execute_code",
    {
      title: "Execute Code",
      description:
        "Runs TypeScript code against the generated, typed API client (import from \\"./client.js\\"). " +
        "Use search_docs first to see available functions and their input types. " +
        "Code runs in an isolated sandbox with network access restricted to the API host only " +
        "(${apiHost}) and no filesystem write access. console.log(...) output is returned as the result.",
      inputSchema: { code: z.string().describe("TypeScript module body. Import functions from \\"./client.js\\" and console.log(...) the result.") },
      annotations: { title: "Execute Code", readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: true },
    },
    async (args) => {
      const { runInSandbox } = await import("./sandbox-runner.js");
      const result = await runInSandbox((args as { code: string }).code, ${JSON.stringify(apiHost)});
      const text = result.stdout + (result.stderr ? \`\\nstderr:\\n\${result.stderr}\` : "");
      return { content: [{ type: "text" as const, text: text || "(no output)" }], isError: !result.ok };
    },
  );`;
}
