// packages/cli/src/emit/emit-dockerfile.ts
//
// MCPFO-12 — emits a minimal, least-privilege Dockerfile for a generated
// streamable-http MCP server. Multi-stage (build → lean runtime), runs as the
// non-root `node` user shipped in the official image, prunes dev deps, and sets
// MCPFORGE_BIND_HOST=0.0.0.0 so the server is reachable through the container's
// published port (host-header validation still restricts callers to localhost,
// so this only widens the network interface, not the accepted Host set).
//
// Only emitted for network transports: a stdio server in a container leaks
// orphaned containers when the client session ends (the CLI enforces this).

// Pin a concrete Node major matching the generated project's engines (>=20);
// bookworm-slim ships a ready-made non-root `node` user.
const NODE_BASE = "node:22-bookworm-slim";

export interface DockerfileOptions {
  port: number;
}

export function emitDockerfile(opts: DockerfileOptions): string {
  const port = opts.port;
  return `# GENERATED by mcpforge (--docker) — minimal least-privilege image for the
# streamable-http MCP server. Build:  docker build -t my-mcp-server .
# Run:    docker run --rm -p ${port}:${port} -e MCPFORGE_BASE_URL=https://api.example.com my-mcp-server

# --- build stage: install all deps and compile TypeScript ---
FROM ${NODE_BASE} AS build
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install
COPY tsconfig.json ./
COPY src ./src
RUN npm run build

# --- runtime stage: production deps only, no toolchain, non-root ---
FROM ${NODE_BASE} AS runtime
ENV NODE_ENV=production
# Reachable through the published port; host-header validation still limits
# callers to localhost, so this widens only the bind interface.
ENV MCPFORGE_BIND_HOST=0.0.0.0
WORKDIR /app
COPY package.json package-lock.json* ./
RUN npm install --omit=dev && npm cache clean --force
COPY --from=build /app/dist ./dist
# Drop privileges: the official image ships a non-root \`node\` user.
USER node
EXPOSE ${port}
CMD ["node", "dist/index.js"]
`;
}

export function emitDockerignore(): string {
  return `node_modules
dist
npm-debug.log
.git
.env
*.local
`;
}
