// Spike 021b — generate a v2 MCP server from getToolsFromOpenApi() DATA.
// Proves ARCHITECTURE.md §37 option (d): klaridian consumes openapi-mcp-generator's
// pure tool DATA (not its v1 code output) and emits a v2 server itself.
// This is a throwaway generator: enough to prove the path end to end, not production.
import { getToolsFromOpenApi } from 'openapi-mcp-generator';
import { jsonSchemaToZod } from 'json-schema-to-zod';
import { writeFileSync } from 'node:fs';

const SPEC = '/Users/ricardo.vasconcelos/projects/klaridian/examples/petstore/openapi.json';
const BASE_URL = 'https://petstore3.swagger.io/api/v3';

const tools = await getToolsFromOpenApi(SPEC);
console.error(`got ${tools.length} tools from spec`);

// Emit a registerTool(...) block per tool. The upstream call is stubbed here
// (the spike is about the MCP/transport layer, not proving HTTP proxying again —
// that already works in the current stdio path). We DO wire the real Zod schema
// generated from each tool's JSON Schema, so schema validation is genuinely exercised.
const toolBlocks = tools.map((t) => {
  const zodSrc = jsonSchemaToZod(t.inputSchema ?? { type: 'object', properties: {} });
  const safeName = JSON.stringify(t.name);
  const desc = JSON.stringify(t.description ?? '');
  // annotations derived from HTTP method — the marketplace-required hints (MCPFO-23)
  const method = (t.method ?? 'get').toLowerCase();
  const readOnly = method === 'get' ? 'true' : 'false';
  const destructive = method === 'delete' ? 'true' : 'false';
  return `  server.registerTool(
    ${safeName},
    {
      description: ${desc},
      inputSchema: ${zodSrc},
      annotations: { readOnlyHint: ${readOnly}, destructiveHint: ${destructive} },
    },
    async (args) => {
      // STUB upstream call — real path would fetch ${method.toUpperCase()} ${t.pathTemplate}
      return { content: [{ type: "text", text: JSON.stringify({ tool: ${safeName}, args, upstream: ${JSON.stringify(BASE_URL + t.pathTemplate)} }) }] };
    },
  );`;
}).join('\n\n');

const serverSrc = `// GENERATED by spike-021b from getToolsFromOpenApi() data — v2 SDK, stateless.
import { createServer } from 'node:http';
import { createMcpHandler, McpServer } from '@modelcontextprotocol/server';
import { toNodeHandler, localhostHostValidation, localhostOriginValidation } from '@modelcontextprotocol/node';
import * as z from 'zod/v4';

const handler = createMcpHandler(() => {
  const server = new McpServer({ name: 'petstore-v2', version: '1.0.0' });

${toolBlocks}

  return server;
});

const nodeHandler = toNodeHandler(handler);
const validateHost = localhostHostValidation();
const validateOrigin = localhostOriginValidation();
createServer((req, res) => {
  if (!validateHost(req, res) || !validateOrigin(req, res)) return;
  void nodeHandler(req, res);
}).listen(3223, '127.0.0.1', () => console.error('petstore-v2 stateless server on http://127.0.0.1:3223/mcp'));
`;

writeFileSync(new URL('./generated-server.mjs', import.meta.url), serverSrc);
console.error('wrote generated-server.mjs (' + serverSrc.length + ' bytes, ' + tools.length + ' tools)');
