// GENERATED by spike-021b from getToolsFromOpenApi() data — v2 SDK, stateless.
import { createServer } from 'node:http';
import { createMcpHandler, McpServer } from '@modelcontextprotocol/server';
import { toNodeHandler, localhostHostValidation, localhostOriginValidation } from '@modelcontextprotocol/node';
import * as z from 'zod/v4';

const handler = createMcpHandler(() => {
  const server = new McpServer({ name: 'petstore-v2', version: '1.0.0' });

  server.registerTool(
    "updatePet",
    {
      description: "Update an existing pet by Id.",
      inputSchema: z.object({ "requestBody": z.record(z.string(), z.any()).describe("Update an existent pet in the store") }),
      annotations: { readOnlyHint: false, destructiveHint: false },
    },
    async (args) => {
      // STUB upstream call — real path would fetch PUT /pet
      return { content: [{ type: "text", text: JSON.stringify({ tool: "updatePet", args, upstream: "https://petstore3.swagger.io/api/v3/pet" }) }] };
    },
  );

  server.registerTool(
    "addPet",
    {
      description: "Add a new pet to the store.",
      inputSchema: z.object({ "requestBody": z.record(z.string(), z.any()).describe("Create a new pet in the store") }),
      annotations: { readOnlyHint: false, destructiveHint: false },
    },
    async (args) => {
      // STUB upstream call — real path would fetch POST /pet
      return { content: [{ type: "text", text: JSON.stringify({ tool: "addPet", args, upstream: "https://petstore3.swagger.io/api/v3/pet" }) }] };
    },
  );

  server.registerTool(
    "findPetsByStatus",
    {
      description: "Multiple status values can be provided with comma separated strings.",
      inputSchema: z.object({ "status": z.enum(["available","pending","sold"]).describe("Status values that need to be considered for filter").default("available") }),
      annotations: { readOnlyHint: true, destructiveHint: false },
    },
    async (args) => {
      // STUB upstream call — real path would fetch GET /pet/findByStatus
      return { content: [{ type: "text", text: JSON.stringify({ tool: "findPetsByStatus", args, upstream: "https://petstore3.swagger.io/api/v3/pet/findByStatus" }) }] };
    },
  );

  server.registerTool(
    "findPetsByTags",
    {
      description: "Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.",
      inputSchema: z.object({ "tags": z.array(z.string()).describe("Tags to filter by") }),
      annotations: { readOnlyHint: true, destructiveHint: false },
    },
    async (args) => {
      // STUB upstream call — real path would fetch GET /pet/findByTags
      return { content: [{ type: "text", text: JSON.stringify({ tool: "findPetsByTags", args, upstream: "https://petstore3.swagger.io/api/v3/pet/findByTags" }) }] };
    },
  );

  server.registerTool(
    "getPetById",
    {
      description: "Returns a single pet.",
      inputSchema: z.object({ "petId": z.number().int().describe("ID of pet to return") }),
      annotations: { readOnlyHint: true, destructiveHint: false },
    },
    async (args) => {
      // STUB upstream call — real path would fetch GET /pet/{petId}
      return { content: [{ type: "text", text: JSON.stringify({ tool: "getPetById", args, upstream: "https://petstore3.swagger.io/api/v3/pet/{petId}" }) }] };
    },
  );

  server.registerTool(
    "updatePetWithForm",
    {
      description: "Updates a pet resource based on the form data.",
      inputSchema: z.object({ "petId": z.number().int().describe("ID of pet that needs to be updated"), "name": z.string().describe("Name of pet that needs to be updated").optional(), "status": z.string().describe("Status of pet that needs to be updated").optional() }),
      annotations: { readOnlyHint: false, destructiveHint: false },
    },
    async (args) => {
      // STUB upstream call — real path would fetch POST /pet/{petId}
      return { content: [{ type: "text", text: JSON.stringify({ tool: "updatePetWithForm", args, upstream: "https://petstore3.swagger.io/api/v3/pet/{petId}" }) }] };
    },
  );

  server.registerTool(
    "deletePet",
    {
      description: "Delete a pet.",
      inputSchema: z.object({ "api_key": z.string().optional(), "petId": z.number().int().describe("Pet id to delete") }),
      annotations: { readOnlyHint: false, destructiveHint: true },
    },
    async (args) => {
      // STUB upstream call — real path would fetch DELETE /pet/{petId}
      return { content: [{ type: "text", text: JSON.stringify({ tool: "deletePet", args, upstream: "https://petstore3.swagger.io/api/v3/pet/{petId}" }) }] };
    },
  );

  server.registerTool(
    "uploadFile",
    {
      description: "Upload image of the pet.",
      inputSchema: z.object({ "petId": z.number().int().describe("ID of pet to update"), "additionalMetadata": z.string().describe("Additional Metadata").optional(), "requestBody": z.string().describe("Request body (content type: application/octet-stream)").optional() }),
      annotations: { readOnlyHint: false, destructiveHint: false },
    },
    async (args) => {
      // STUB upstream call — real path would fetch POST /pet/{petId}/uploadImage
      return { content: [{ type: "text", text: JSON.stringify({ tool: "uploadFile", args, upstream: "https://petstore3.swagger.io/api/v3/pet/{petId}/uploadImage" }) }] };
    },
  );

  server.registerTool(
    "getInventory",
    {
      description: "Returns a map of status codes to quantities.",
      inputSchema: z.object({}),
      annotations: { readOnlyHint: true, destructiveHint: false },
    },
    async (args) => {
      // STUB upstream call — real path would fetch GET /store/inventory
      return { content: [{ type: "text", text: JSON.stringify({ tool: "getInventory", args, upstream: "https://petstore3.swagger.io/api/v3/store/inventory" }) }] };
    },
  );

  server.registerTool(
    "placeOrder",
    {
      description: "Place a new order in the store.",
      inputSchema: z.object({ "requestBody": z.record(z.string(), z.any()).describe("The JSON request body.").optional() }),
      annotations: { readOnlyHint: false, destructiveHint: false },
    },
    async (args) => {
      // STUB upstream call — real path would fetch POST /store/order
      return { content: [{ type: "text", text: JSON.stringify({ tool: "placeOrder", args, upstream: "https://petstore3.swagger.io/api/v3/store/order" }) }] };
    },
  );

  server.registerTool(
    "getOrderById",
    {
      description: "For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.",
      inputSchema: z.object({ "orderId": z.number().int().describe("ID of order that needs to be fetched") }),
      annotations: { readOnlyHint: true, destructiveHint: false },
    },
    async (args) => {
      // STUB upstream call — real path would fetch GET /store/order/{orderId}
      return { content: [{ type: "text", text: JSON.stringify({ tool: "getOrderById", args, upstream: "https://petstore3.swagger.io/api/v3/store/order/{orderId}" }) }] };
    },
  );

  server.registerTool(
    "deleteOrder",
    {
      description: "For valid response try integer IDs with value < 1000. Anything above 1000 or non-integers will generate API errors.",
      inputSchema: z.object({ "orderId": z.number().int().describe("ID of the order that needs to be deleted") }),
      annotations: { readOnlyHint: false, destructiveHint: true },
    },
    async (args) => {
      // STUB upstream call — real path would fetch DELETE /store/order/{orderId}
      return { content: [{ type: "text", text: JSON.stringify({ tool: "deleteOrder", args, upstream: "https://petstore3.swagger.io/api/v3/store/order/{orderId}" }) }] };
    },
  );

  server.registerTool(
    "createUser",
    {
      description: "This can only be done by the logged in user.",
      inputSchema: z.object({ "requestBody": z.record(z.string(), z.any()).describe("Created user object").optional() }),
      annotations: { readOnlyHint: false, destructiveHint: false },
    },
    async (args) => {
      // STUB upstream call — real path would fetch POST /user
      return { content: [{ type: "text", text: JSON.stringify({ tool: "createUser", args, upstream: "https://petstore3.swagger.io/api/v3/user" }) }] };
    },
  );

  server.registerTool(
    "createUsersWithListInput",
    {
      description: "Creates list of users with given input array.",
      inputSchema: z.object({ "requestBody": z.array(z.record(z.string(), z.any())).describe("The JSON request body.").optional() }),
      annotations: { readOnlyHint: false, destructiveHint: false },
    },
    async (args) => {
      // STUB upstream call — real path would fetch POST /user/createWithList
      return { content: [{ type: "text", text: JSON.stringify({ tool: "createUsersWithListInput", args, upstream: "https://petstore3.swagger.io/api/v3/user/createWithList" }) }] };
    },
  );

  server.registerTool(
    "loginUser",
    {
      description: "Log into the system.",
      inputSchema: z.object({ "username": z.string().describe("The user name for login").optional(), "password": z.string().describe("The password for login in clear text").optional() }),
      annotations: { readOnlyHint: true, destructiveHint: false },
    },
    async (args) => {
      // STUB upstream call — real path would fetch GET /user/login
      return { content: [{ type: "text", text: JSON.stringify({ tool: "loginUser", args, upstream: "https://petstore3.swagger.io/api/v3/user/login" }) }] };
    },
  );

  server.registerTool(
    "logoutUser",
    {
      description: "Log user out of the system.",
      inputSchema: z.object({}),
      annotations: { readOnlyHint: true, destructiveHint: false },
    },
    async (args) => {
      // STUB upstream call — real path would fetch GET /user/logout
      return { content: [{ type: "text", text: JSON.stringify({ tool: "logoutUser", args, upstream: "https://petstore3.swagger.io/api/v3/user/logout" }) }] };
    },
  );

  server.registerTool(
    "getUserByName",
    {
      description: "Get user detail based on username.",
      inputSchema: z.object({ "username": z.string().describe("The name that needs to be fetched. Use user1 for testing") }),
      annotations: { readOnlyHint: true, destructiveHint: false },
    },
    async (args) => {
      // STUB upstream call — real path would fetch GET /user/{username}
      return { content: [{ type: "text", text: JSON.stringify({ tool: "getUserByName", args, upstream: "https://petstore3.swagger.io/api/v3/user/{username}" }) }] };
    },
  );

  server.registerTool(
    "updateUser",
    {
      description: "This can only be done by the logged in user.",
      inputSchema: z.object({ "username": z.string().describe("name that need to be deleted"), "requestBody": z.record(z.string(), z.any()).describe("Update an existent user in the store").optional() }),
      annotations: { readOnlyHint: false, destructiveHint: false },
    },
    async (args) => {
      // STUB upstream call — real path would fetch PUT /user/{username}
      return { content: [{ type: "text", text: JSON.stringify({ tool: "updateUser", args, upstream: "https://petstore3.swagger.io/api/v3/user/{username}" }) }] };
    },
  );

  server.registerTool(
    "deleteUser",
    {
      description: "This can only be done by the logged in user.",
      inputSchema: z.object({ "username": z.string().describe("The name that needs to be deleted") }),
      annotations: { readOnlyHint: false, destructiveHint: true },
    },
    async (args) => {
      // STUB upstream call — real path would fetch DELETE /user/{username}
      return { content: [{ type: "text", text: JSON.stringify({ tool: "deleteUser", args, upstream: "https://petstore3.swagger.io/api/v3/user/{username}" }) }] };
    },
  );

  return server;
});

const nodeHandler = toNodeHandler(handler);
const validateHost = localhostHostValidation();
const validateOrigin = localhostOriginValidation();
createServer((req, res) => {
  if (!validateHost(req, res) || !validateOrigin(req, res)) return;
  void nodeHandler(req, res);
}).listen(3223, '127.0.0.1', () => console.error('petstore-v2 stateless server on http://127.0.0.1:3223/mcp'));
