// packages/cli/src/emit/python/emit-python-codemode.ts
//
// MCPFO-55 (ARCHITECTURE.md §104): SDK code mode for the Python target.
//
// The model-written code is TypeScript, NOT Python, run by the same Deno
// sandbox the TypeScript target uses (emit-sandbox.ts). Only the host process
// differs: a Python server spawns `deno run` instead of a Node server doing it.
// Why TS and not Python: CPython has no capability sandbox. An in-process
// sandbox was escaped in spike 062 (§86), wasmtime-py cannot scope egress to
// one host, and Pydantic archived its Pyodide-in-Deno runner as unsafe. The
// code is written by the model, never by the server's operator, so its
// language does not have to match the server's.
//
// Deno reaches the project as a normal pip dependency (`deno` on PyPI,
// published by denoland/deno_pypi via Trusted Publishing; its binary is
// byte-identical to the GitHub release). The typed client is the exact
// `client.ts` the TS target emits (emit-client.ts). Deno runs TypeScript
// natively, so there is no build step; its one npm dependency (zod) is
// installed once into `sandbox/node_modules` by `python sandbox_runner.py
// --install`, and every sandboxed run is `--no-remote --cached-only`, so model
// code cannot fetch modules at runtime.
//
// Emitted files: sandbox_runner.py, sandbox/client.ts, sandbox/deno.json, and
// a tools.py that registers the two code-mode tools (search_docs +
// execute_code) in the same TOOLS shape server.py already consumes, so
// server.py, conformance.py and plugin dispatch wrapping are unchanged.

import type { ToolIR } from "../ir.js";
import { emitClientModule, sanitizeFunctionName, dedupeFunctionNames } from "../emit-client.js";
import { buildOperationDocs } from "../emit-docs.js";
import { extractApiHost } from "../emit-sandbox.js";

/** Deno pip pin for a code-mode Python project. The wheel ships the official
 *  Deno binary; the lower bound is the version the sandbox flags were verified on. */
export const DENO_PIP_SPEC = ">=2.9,<3";

/** zod version the typed client imports inside the sandbox (matches the TS target). */
const SANDBOX_ZOD_SPEC = "^4.2.0";

function pyStr(s: string): string {
  return JSON.stringify(s);
}

function pyJsonValue(value: unknown): string {
  return `json.loads(${JSON.stringify(JSON.stringify(value))})`;
}

/** sandbox/deno.json: maps the bare `zod` import to npm and keeps packages in a local node_modules. */
export function emitSandboxDenoJson(): string {
  return (
    JSON.stringify(
      {
        imports: { zod: `npm:zod@${SANDBOX_ZOD_SPEC}` },
        nodeModulesDir: "auto",
      },
      null,
      2
    ) + "\n"
  );
}

/** sandbox_runner.py: installs the sandbox's dependencies once, then runs model code in Deno. */
export function emitSandboxRunnerPy(): string {
  return `# GENERATED by klaridian (Python code mode, MCPFO-55) — do not edit.
#
# Runs model-written TypeScript against the typed API client (sandbox/client.ts)
# in a Deno subprocess with an explicit, minimal permission set:
#   --allow-net=<API host>   network to the upstream API only
#   --allow-read=sandbox/    read the client and its installed dependencies only
#   --allow-env=KLARIDIAN_BASE_URL,KLARIDIAN_AUTH_TOKEN   the two vars the client reads
#   --no-remote --cached-only   no module downloads at run time (a remote import
#                               would be an egress channel outside the API host)
# No write, run, ffi or sys permission. The same model as the TypeScript target.
#
# Deno comes from the \`deno\` pip package (requirements.txt). Run
# \`python sandbox_runner.py --install\` once, with network access, to install the
# client's one npm dependency (zod) into sandbox/node_modules.
import asyncio
import os
import shutil
import subprocess
import sys
from pathlib import Path

SANDBOX_DIR = Path(__file__).resolve().parent / "sandbox"
# Deno's own cache lives inside the sandbox dir, so the read permission above
# covers everything the program needs and nothing else.
DENO_DIR = SANDBOX_DIR / ".deno"
# Per-run limits. Wall clock kills a hung script; the V8 heap cap stops one
# script from exhausting the server's memory.
TIMEOUT_SECONDS = float(os.environ.get("KLARIDIAN_SANDBOX_TIMEOUT", "30"))
MAX_HEAP_MB = int(os.environ.get("KLARIDIAN_SANDBOX_MAX_HEAP_MB", "256"))


def deno_bin() -> str:
    try:
        from deno import find_deno_bin  # the pip-installed official binary

        return str(find_deno_bin())
    except Exception:  # noqa: BLE001 — fall back to a system install
        found = shutil.which("deno")
        if found:
            return found
        raise RuntimeError("Deno not found: pip install -r requirements.txt (it provides the deno package).")


def _base_env() -> dict:
    # Only what Deno itself needs. Nothing else from this process's environment
    # (other secrets, API keys) reaches the sandboxed program.
    return {
        "PATH": os.environ.get("PATH", ""),
        "DENO_DIR": str(DENO_DIR),
        "DENO_NO_UPDATE_CHECK": "1",
    }


def is_installed() -> bool:
    return (SANDBOX_DIR / "node_modules").is_dir()


def install() -> None:
    subprocess.run([deno_bin(), "install"], cwd=SANDBOX_DIR, env=_base_env(), check=True)


async def run_in_sandbox(code: str, api_host: str) -> tuple[bool, str, str]:
    """Runs code in Deno. Returns (ok, stdout, stderr); never raises for a
    failed script, so the tool can report it to the model as a tool error."""
    if not is_installed():
        return (
            False,
            "",
            "The code sandbox is not installed. Run \`python sandbox_runner.py --install\` once in the server directory.",
        )
    args = [
        deno_bin(),
        "run",
        "--no-prompt",
        "--no-remote",
        "--cached-only",
        f"--allow-net={api_host}",
        f"--allow-read={SANDBOX_DIR}",
        "--allow-env=KLARIDIAN_BASE_URL,KLARIDIAN_AUTH_TOKEN",
        f"--v8-flags=--max-old-space-size={MAX_HEAP_MB}",
        "-",  # read the program from stdin
    ]
    env = _base_env()
    env["KLARIDIAN_BASE_URL"] = os.environ.get("KLARIDIAN_BASE_URL", "")
    env["KLARIDIAN_AUTH_TOKEN"] = os.environ.get("KLARIDIAN_AUTH_TOKEN", "")
    proc = await asyncio.create_subprocess_exec(
        *args,
        cwd=SANDBOX_DIR,
        env=env,
        stdin=asyncio.subprocess.PIPE,
        stdout=asyncio.subprocess.PIPE,
        stderr=asyncio.subprocess.PIPE,
    )
    try:
        out, err = await asyncio.wait_for(proc.communicate(code.encode("utf-8")), TIMEOUT_SECONDS)
    except asyncio.TimeoutError:
        proc.kill()
        await proc.wait()
        return False, "", f"Execution timed out after {TIMEOUT_SECONDS:g}s."
    return proc.returncode == 0, out.decode("utf-8", "replace"), err.decode("utf-8", "replace")


if __name__ == "__main__":
    if "--install" in sys.argv[1:]:
        install()
        print(f"Sandbox dependencies installed in {SANDBOX_DIR / 'node_modules'}", file=sys.stderr)
    else:
        print("usage: python sandbox_runner.py --install", file=sys.stderr)
        sys.exit(2)
`;
}

/** tools.py for a code-mode project: the search_docs + execute_code pair, in the TOOLS shape server.py consumes. */
export function emitCodeModeToolsModule(tools: ToolIR[], baseUrl: string): string {
  const apiHost = extractApiHost(baseUrl);
  const functionNames = dedupeFunctionNames(tools.map((t) => sanitizeFunctionName(t.operationId || t.name)));
  const docs = buildOperationDocs(tools, functionNames);

  const executeDescription =
    'Runs TypeScript code against the generated, typed API client (import from "./client.ts"). ' +
    `Code runs in an isolated Deno sandbox with network access restricted to the API host only (${apiHost}) ` +
    "and no filesystem write access. console.log(...) output is returned as the result.";
  const searchDescription =
    "Searches the generated API client's operation documentation (function names, HTTP method/path, parameter shapes). " +
    "Use this before execute_code to find the right function and its input shape. Case-insensitive substring match; " +
    "an empty query returns every operation.";

  return `# GENERATED by klaridian (Python code mode, MCPFO-55) — do not edit.
#
# Code mode exposes two tools instead of one per operation: search_docs (find
# the right client function) and execute_code (run TypeScript that calls it,
# inside the Deno sandbox — see sandbox_runner.py).
import json

from mcp import types

from sandbox_runner import run_in_sandbox

API_HOST = ${pyStr(apiHost)}

# Per-operation docs for search_docs, computed at generation time from the spec
# (structural summary when the spec has no description; no LLM involved).
OPERATION_DOCS: list[dict] = ${pyJsonValue(docs)}


async def _call_search_docs(arguments: dict) -> types.CallToolResult:
    query = (arguments.get("query") or "").strip().lower()
    matches = [
        d
        for d in OPERATION_DOCS
        if not query
        or query in d["functionName"].lower()
        or query in d["path"].lower()
        or query in d["doc"].lower()
    ]
    if not matches:
        text = (
            f'No operations matched "{query}". {len(OPERATION_DOCS)} operation(s) total — '
            "try search_docs with an empty query to list them all."
        )
        return types.CallToolResult(content=[types.TextContent(type="text", text=text)])
    blocks = []
    for d in matches:
        note = "" if d["hasRealDescription"] else " (structural summary — no description in the source spec)"
        blocks.append(f"### {d['functionName']}\\n{d['method']} {d['path']}{note}\\n\\n{d['doc']}")
    return types.CallToolResult(content=[types.TextContent(type="text", text="\\n\\n---\\n\\n".join(blocks))])


async def _call_execute_code(arguments: dict) -> types.CallToolResult:
    ok, stdout, stderr = await run_in_sandbox(arguments.get("code", ""), API_HOST)
    text = stdout + (f"\\nstderr:\\n{stderr}" if stderr else "")
    return types.CallToolResult(
        content=[types.TextContent(type="text", text=text or "(no output)")],
        is_error=not ok,
    )


TOOLS: list[dict] = [
    {
        "name": "execute_code",
        "title": "Execute Code",
        "description": ${pyStr(executeDescription)},
        "input_schema": ${pyJsonValue({
          type: "object",
          properties: {
            code: {
              type: "string",
              description: 'TypeScript module body. Import functions from "./client.ts" and console.log(...) the result.',
            },
          },
          required: ["code"],
        })},
        "output_schema": None,
        "annotations": types.ToolAnnotations(
            title="Execute Code",
            read_only_hint=False,
            destructive_hint=False,
            idempotent_hint=False,
            open_world_hint=True,
        ),
        "call": _call_execute_code,
    },
    {
        "name": "search_docs",
        "title": "Search Docs",
        "description": ${pyStr(searchDescription)},
        "input_schema": ${pyJsonValue({
          type: "object",
          properties: {
            query: {
              type: "string",
              description:
                "Search text, e.g. a function name, resource, or keyword. Omit or pass an empty string to list every operation.",
            },
          },
        })},
        "output_schema": None,
        "annotations": types.ToolAnnotations(
            title="Search Docs",
            read_only_hint=True,
            destructive_hint=False,
            idempotent_hint=True,
            open_world_hint=False,
        ),
        "call": _call_search_docs,
    },
]
`;
}

/** Every file code mode adds to (or replaces in) a Python project. */
export function emitPythonCodeModeFiles(tools: ToolIR[], baseUrl: string): Record<string, string> {
  return {
    "tools.py": emitCodeModeToolsModule(tools, baseUrl),
    "sandbox_runner.py": emitSandboxRunnerPy(),
    "sandbox/client.ts": emitClientModule(tools),
    "sandbox/deno.json": emitSandboxDenoJson(),
  };
}
