// packages/cli/src/plugins/mixpanel/mixpanel.plugin.ts
//
// Product-observability plugin #3 (ARCHITECTURE.md section 26). Mirrors
// posthog.plugin.ts/amplitude.plugin.ts's shape closely: same
// ObservabilityPlugin interface, same vendored-file pattern, same
// one-event-per-tool-call scope.
//
// stdio-safety note (checked directly against the installed package, not
// assumed — see ARCHITECTURE.md section 26): the `mixpanel` (mixpanel-node)
// package has zero console.log/console.dir/console.info call sites in its
// published code — it only ever reports errors via callback, never writes
// to stdout on its own. No ConsoleSpanExporter-style landmine here either.

import type {
  ObservabilityPlugin,
  PluginConfigField,
  ResolvedPluginConfig,
  TemplateContribution,
} from "../plugin.interface.js";

const CONFIG_SCHEMA: PluginConfigField[] = [];

function generateInstrumentationFile(_config: ResolvedPluginConfig): string {
  return `// GENERATED by klaridian (mixpanel plugin) — vendored instrumentation helper.
// Captures one "mcp tool called" event per tool call: name, duration,
// success/error. The \`mixpanel\` (mixpanel-node) package has zero
// console.log/dir/info call sites in its published code (verified
// directly — see ARCHITECTURE.md section 26) — it only reports errors via
// callback, never writes to stdout on its own. Safe alongside stdio MCP
// transport for the same reason the OTel/PostHog/Amplitude plugins are
// (see spike/FINDINGS.md for why that distinction matters).

import Mixpanel from "mixpanel";

const TOKEN = process.env.MIXPANEL_TOKEN;
if (!TOKEN) {
  console.error(
    "Missing required environment variable MIXPANEL_TOKEN. " +
      "Set it to your Mixpanel project token to enable product observability, " +
      "or remove the mixpanel plugin at generation time if you don't want it."
  );
  process.exit(1);
}

const mixpanel = Mixpanel.init(TOKEN);

/**
 * Wraps an MCP tool handler to capture a Mixpanel product-analytics event
 * per call. Every generated tool is wired through this — no per-tool
 * custom instrumentation code needed, mirroring the OTel/PostHog/Amplitude
 * plugins' wrapTool functions.
 *
 * No explicit flush/shutdown handler here, unlike PostHog/Amplitude:
 * mixpanel-node's track() sends each event over HTTP immediately rather
 * than batching client-side, so there's no in-memory queue that could be
 * lost on process exit (confirmed against the installed package, not
 * assumed) — a real difference between SDKs, not an oversight.
 */
export function wrapMixpanelTool<T extends (args: any) => Promise<unknown>>(toolName: string, handler: T): T {
  return (async (args: any) => {
    const startedAt = Date.now();
    // A fixed distinct_id is a deliberate v0 simplification, mirroring the
    // PostHog/Amplitude plugins: a generated stdio MCP server has no
    // notion of an end-user identity (the caller is an MCP client, not a
    // logged-in human) — every event is attributed to the server itself.
    const distinctId = "mcp-server";
    try {
      const result = await handler(args);
      mixpanel.track("mcp tool called", {
        distinct_id: distinctId,
        tool_name: toolName,
        duration_ms: Date.now() - startedAt,
        success: true,
      });
      return result;
    } catch (err) {
      mixpanel.track("mcp tool called", {
        distinct_id: distinctId,
        tool_name: toolName,
        duration_ms: Date.now() - startedAt,
        success: false,
        error_message: String(err),
      });
      throw err;
    }
  }) as T;
}
`;
}

export const mixpanelPlugin: ObservabilityPlugin = {
  id: "mixpanel",
  name: "Mixpanel (product observability)",
  configSchema: CONFIG_SCHEMA,

  getTemplateContributions(config: ResolvedPluginConfig): TemplateContribution[] {
    return [
      {
        path: "src/instrumentation/mixpanel.ts",
        content: generateInstrumentationFile(config),
      },
    ];
  },

  getDependencies(): Record<string, string> {
    return {
      mixpanel: "^0.23.0",
    };
  },

  getServerWiring() {
    return {
      importStatement: `import { wrapMixpanelTool } from "./instrumentation/mixpanel.js";`,
      wrapFunctionName: "wrapMixpanelTool",
    };
  },
};
