// packages/cli/src/plugins/otel/otel.plugin.ts
//
// The generic OpenTelemetry observability plugin (ARCHITECTURE.md sections
// 4-5, decided as the first plugin in PLAN.md section 5). Contributes a
// vendored instrumentation.ts file to the generated project (per
// ARCHITECTURE.md section 10 — vendored-file for v0, not a published
// runtime-otel package yet) plus the wiring to wrap every tool handler.
//
// Directly incorporates both findings from spike/FINDINGS.md:
// 1. Uses OTLPTraceExporter — NEVER ConsoleSpanExporter — because
//    ConsoleSpanExporter writes to stdout, which corrupts the stdio-transport
//    MCP JSON-RPC stream. Any OTel diagnostics are routed to stderr.
// 2. Wires SIGINT/SIGTERM handlers that call sdk.shutdown() explicitly,
//    because the default BatchSpanProcessor can lose spans on process exit
//    otherwise (observed directly in the spike).

import type {
  ObservabilityPlugin,
  PluginConfigField,
  ResolvedPluginConfig,
  TemplateContribution,
} from "../plugin.interface.js";

const CONFIG_SCHEMA: PluginConfigField[] = [
  {
    key: "otlpEndpoint",
    prompt: "OTLP HTTP trace endpoint to export spans to",
    default: "http://localhost:4318/v1/traces",
    required: true,
  },
  {
    key: "serviceName",
    prompt: "Service name to report in traces",
    required: true,
  },
];

function generateInstrumentationFile(config: ResolvedPluginConfig): string {
  return `// GENERATED by mcpforge (otel plugin) — vendored instrumentation helper.
// See spike/FINDINGS.md in the mcpforge repo for why this file is shaped
// the way it is: ConsoleSpanExporter corrupts stdio MCP transports, and
// span flushing needs explicit shutdown handling.

import { NodeSDK } from "@opentelemetry/sdk-node";
import { OTLPTraceExporter } from "@opentelemetry/exporter-trace-otlp-http";
import { trace, SpanStatusCode, diag, DiagConsoleLogger, DiagLogLevel } from "@opentelemetry/api";

// Route OTel's own internal diagnostics to stderr explicitly — never stdout,
// which must carry only JSON-RPC for stdio-transport MCP servers.
diag.setLogger(new DiagConsoleLogger(), DiagLogLevel.ERROR);

const OTLP_ENDPOINT = process.env.OTEL_EXPORTER_OTLP_ENDPOINT || ${JSON.stringify(config.otlpEndpoint)};

const sdk = new NodeSDK({
  serviceName: ${JSON.stringify(config.serviceName)},
  traceExporter: new OTLPTraceExporter({ url: OTLP_ENDPOINT }),
});

sdk.start();

// Ensure spans are flushed on exit, whether the process ends normally or is
// signaled — the default batch processor can otherwise lose spans on exit.
process.on("SIGINT", () => sdk.shutdown().finally(() => process.exit(0)));
process.on("SIGTERM", () => sdk.shutdown().finally(() => process.exit(0)));

const tracer = trace.getTracer(${JSON.stringify(config.serviceName)});

/**
 * Wraps an MCP tool handler in an OTel span. Every generated tool is wired
 * through this — no per-tool custom instrumentation code needed
 * (ARCHITECTURE.md section 5).
 */
export function wrapTool<T extends (args: any) => Promise<unknown>>(toolName: string, handler: T): T {
  return (async (args: any) => {
    return tracer.startActiveSpan(\`mcp.tool.call \${toolName}\`, async (span) => {
      span.setAttribute("mcp.tool.name", toolName);
      span.setAttribute("mcp.tool.arguments", JSON.stringify(args));
      try {
        const result = await handler(args);
        span.setStatus({ code: SpanStatusCode.OK });
        return result;
      } catch (err) {
        span.setStatus({ code: SpanStatusCode.ERROR, message: String(err) });
        span.recordException(err as Error);
        throw err;
      } finally {
        span.end();
      }
    });
  }) as T;
}
`;
}

export const otelPlugin: ObservabilityPlugin = {
  id: "otel",
  name: "OpenTelemetry (generic)",
  configSchema: CONFIG_SCHEMA,

  getTemplateContributions(config: ResolvedPluginConfig): TemplateContribution[] {
    return [
      {
        path: "src/instrumentation/otel.ts",
        content: generateInstrumentationFile(config),
      },
    ];
  },

  getDependencies(): Record<string, string> {
    return {
      "@opentelemetry/api": "^1.9.0",
      "@opentelemetry/sdk-node": "^0.222.0",
      "@opentelemetry/exporter-trace-otlp-http": "^0.222.0",
    };
  },

  getServerWiring() {
    return {
      importStatement: `import { wrapTool } from "./instrumentation/otel.js";`,
      wrapFunctionName: "wrapTool",
    };
  },
};
