// packages/cli/src/plugins/otel/otel.plugin.ts
//
// The generic OpenTelemetry observability plugin (ARCHITECTURE.md sections
// 4-5, decided as the first plugin in PLAN.md section 5). Contributes a
// vendored instrumentation.ts file to the generated project (per
// ARCHITECTURE.md section 10 — vendored-file for v0, not a published
// runtime-otel package yet) plus the wiring to wrap every tool handler.
//
// Directly incorporates both findings from spikes/001-otel-mechanic/FINDINGS.md:
// 1. Uses OTLPTraceExporter — NEVER ConsoleSpanExporter — because
//    ConsoleSpanExporter writes to stdout, which corrupts the stdio-transport
//    MCP JSON-RPC stream. Any OTel diagnostics are routed to stderr.
// 2. Wires SIGINT/SIGTERM handlers that call sdk.shutdown() explicitly,
//    because the default BatchSpanProcessor can lose spans on process exit
//    otherwise (observed directly in the spike).

import type {
  ObservabilityPlugin,
  PluginConfigField,
  ResolvedPluginConfig,
  TemplateContribution,
} from "../plugin.interface.js";

const CONFIG_SCHEMA: PluginConfigField[] = [
  {
    key: "otlpEndpoint",
    prompt: "OTLP HTTP trace endpoint to export spans to",
    default: "http://localhost:4318/v1/traces",
    required: true,
  },
  {
    key: "serviceName",
    prompt: "Service name to report in traces",
    required: true,
  },
  {
    key: "argumentCapture",
    prompt: "How to record tool arguments in spans: redacted (names only) | none | full",
    default: "redacted",
    required: false,
  },
  {
    key: "redactFields",
    prompt: "Comma-separated argument field names to mask when argumentCapture=full",
    default: "password,token,secret,authorization,apiKey,api_key,ssn",
    required: false,
  },
];

/**
 * Emits the span attribute lines that record tool arguments, honoring the
 * GDPR-minimizing capture policy. Default "redacted" records argument NAMES
 * only (never values), so a third-party OTLP backend never receives PII by
 * default (MCPFO-24).
 */
function emitArgumentCapture(config: ResolvedPluginConfig): string {
  const mode = config.argumentCapture ?? "redacted";
  if (mode === "none") {
    return "      // argumentCapture=none: tool arguments are not recorded.";
  }
  if (mode === "redacted") {
    return '      // argumentCapture=redacted (default): record argument NAMES only, never values.\n' +
      '      span.setAttribute("mcp.tool.argument_names", Object.keys(args ?? {}).join(","));';
  }
  if (mode === "full") {
    const fields = (config.redactFields ?? "")
      .split(",")
      .map((f) => f.trim())
      .filter(Boolean);
    return (
      `      // argumentCapture=full: record values, masking sensitive fields.\n` +
      `      const REDACT_FIELDS = new Set(${JSON.stringify(fields)});\n` +
      `      const redacted = Object.fromEntries(\n` +
      `        Object.entries(args ?? {}).map(([k, v]) => [k, REDACT_FIELDS.has(k) ? "[REDACTED]" : v])\n` +
      `      );\n` +
      `      span.setAttribute("mcp.tool.arguments", JSON.stringify(redacted));`
    );
  }
  throw new Error(
    `Plugin "otel": invalid argumentCapture "${mode}" — expected one of: redacted, none, full.`
  );
}

function generateInstrumentationFile(config: ResolvedPluginConfig): string {
  return `// GENERATED by klaridian (otel plugin) — vendored instrumentation helper.
// See spikes/001-otel-mechanic/FINDINGS.md in the klaridian repo for why this file is shaped
// the way it is: ConsoleSpanExporter corrupts stdio MCP transports, and
// span flushing needs explicit shutdown handling.

import { NodeSDK } from "@opentelemetry/sdk-node";
import { OTLPTraceExporter } from "@opentelemetry/exporter-trace-otlp-http";
import { trace, SpanStatusCode, diag, DiagConsoleLogger, DiagLogLevel } from "@opentelemetry/api";

// Route OTel's own internal diagnostics to stderr explicitly — never stdout,
// which must carry only JSON-RPC for stdio-transport MCP servers.
diag.setLogger(new DiagConsoleLogger(), DiagLogLevel.ERROR);

const OTLP_ENDPOINT = process.env.OTEL_EXPORTER_OTLP_ENDPOINT || ${JSON.stringify(config.otlpEndpoint)};

const sdk = new NodeSDK({
  serviceName: ${JSON.stringify(config.serviceName)},
  traceExporter: new OTLPTraceExporter({ url: OTLP_ENDPOINT }),
});

sdk.start();

// Ensure spans are flushed on exit, whether the process ends normally or is
// signaled — the default batch processor can otherwise lose spans on exit.
process.on("SIGINT", () => sdk.shutdown().finally(() => process.exit(0)));
process.on("SIGTERM", () => sdk.shutdown().finally(() => process.exit(0)));

const tracer = trace.getTracer(${JSON.stringify(config.serviceName)});

/**
 * Wraps an MCP tool handler in an OTel span. Every generated tool is wired
 * through this — no per-tool custom instrumentation code needed
 * (ARCHITECTURE.md section 5).
 */
export function wrapTool<T extends (args: any) => Promise<unknown>>(toolName: string, handler: T): T {
  return (async (args: any) => {
    return tracer.startActiveSpan(\`mcp.tool.call \${toolName}\`, async (span) => {
      span.setAttribute("mcp.tool.name", toolName);
${emitArgumentCapture(config)}
      try {
        const result = await handler(args);
        span.setStatus({ code: SpanStatusCode.OK });
        return result;
      } catch (err) {
        span.setStatus({ code: SpanStatusCode.ERROR, message: String(err) });
        span.recordException(err as Error);
        throw err;
      } finally {
        span.end();
      }
    });
  }) as T;
}
`;
}

export const otelPlugin: ObservabilityPlugin = {
  id: "otel",
  name: "OpenTelemetry (generic)",
  configSchema: CONFIG_SCHEMA,

  getTemplateContributions(config: ResolvedPluginConfig): TemplateContribution[] {
    return [
      {
        path: "src/instrumentation/otel.ts",
        content: generateInstrumentationFile(config),
      },
    ];
  },

  getDependencies(): Record<string, string> {
    return {
      "@opentelemetry/api": "^1.9.0",
      "@opentelemetry/sdk-node": "^0.222.0",
      "@opentelemetry/exporter-trace-otlp-http": "^0.222.0",
    };
  },

  getServerWiring() {
    return {
      importStatement: `import { wrapTool } from "./instrumentation/otel.js";`,
      wrapFunctionName: "wrapTool",
    };
  },
};
