// packages/cli/test/product-analytics-plugins.test.ts
//
// Guards the shared product-analytics template refactor (ARCHITECTURE.md
// section 58): the three product-analytics plugins (posthog, amplitude,
// mixpanel) assemble their vendored instrumentation file from one shared
// helper (src/plugins/shared/product-analytics-template.ts) instead of three
// near-identical hand-written generators. These tests lock the emitted file's
// structure per plugin so a future template change can't silently drop a
// plugin's credential guard, wrap function, or provider-specific capture call.
//
// The vendored FILES stay per-plugin (PLAN.md section 7 auditability rule);
// only klaridian's generator code was deduplicated. So each plugin's output
// must still be complete and self-contained — that's exactly what's asserted.

import { test } from "node:test";
import assert from "node:assert/strict";
import { resolvePluginConfig } from "../src/plugins/plugin.interface.js";
import { posthogPlugin } from "../src/plugins/posthog/posthog.plugin.js";
import { amplitudePlugin } from "../src/plugins/amplitude/amplitude.plugin.js";
import { mixpanelPlugin } from "../src/plugins/mixpanel/mixpanel.plugin.js";
import type { ObservabilityPlugin } from "../src/plugins/plugin.interface.js";

function vendoredFile(plugin: ObservabilityPlugin): string {
  const config = resolvePluginConfig(plugin, {});
  const contributions = plugin.getTemplateContributions(config);
  assert.equal(contributions.length, 1, `${plugin.id}: exactly one contributed file`);
  const c = contributions[0];
  assert.equal(c.path, `src/instrumentation/${plugin.id}.ts`, `${plugin.id}: namespaced path`);
  return typeof c.content === "function" ? c.content(config) : c.content;
}

const CASES: {
  plugin: ObservabilityPlugin;
  credentialEnvVar: string;
  wrapFn: string;
  importFragment: string;
  captureFragment: string;
  hasFlushHandlers: boolean;
}[] = [
  {
    plugin: posthogPlugin,
    credentialEnvVar: "POSTHOG_API_KEY",
    wrapFn: "wrapPostHogTool",
    importFragment: 'import { PostHog } from "posthog-node";',
    captureFragment: "posthog.capture({",
    hasFlushHandlers: true,
  },
  {
    plugin: amplitudePlugin,
    credentialEnvVar: "AMPLITUDE_API_KEY",
    wrapFn: "wrapAmplitudeTool",
    importFragment: 'import { init, track, flush } from "@amplitude/analytics-node";',
    captureFragment: "device_id:",
    hasFlushHandlers: true,
  },
  {
    plugin: mixpanelPlugin,
    credentialEnvVar: "MIXPANEL_TOKEN",
    wrapFn: "wrapMixpanelTool",
    importFragment: 'import Mixpanel from "mixpanel";',
    captureFragment: 'mixpanel.track("mcp tool called"',
    hasFlushHandlers: false,
  },
];

for (const cse of CASES) {
  test(`${cse.plugin.id}: vendored file is complete and self-contained`, () => {
    const file = vendoredFile(cse.plugin);

    // Header identifies the plugin
    assert.match(file, new RegExp(`GENERATED by klaridian \\(${cse.plugin.id} plugin\\)`));
    // Provider SDK import
    assert.ok(file.includes(cse.importFragment), `${cse.plugin.id}: provider import present`);
    // Missing-credential guard that exits loudly
    assert.ok(file.includes(`process.env.${cse.credentialEnvVar}`), `${cse.plugin.id}: reads credential env var`);
    assert.match(file, /process\.exit\(1\)/, `${cse.plugin.id}: exits if credential missing`);
    // The exported wrap function matches getServerWiring()
    assert.ok(file.includes(`export function ${cse.wrapFn}<`), `${cse.plugin.id}: exports wrap fn`);
    assert.equal(cse.plugin.getServerWiring().wrapFunctionName, cse.wrapFn);
    assert.ok(
      cse.plugin.getServerWiring().importStatement.includes(cse.wrapFn),
      `${cse.plugin.id}: wiring import references the wrap fn`
    );
    // Both success and error paths capture an event
    assert.ok(file.includes(cse.captureFragment), `${cse.plugin.id}: provider-specific capture call present`);
    assert.match(file, /success: true/, `${cse.plugin.id}: success path`);
    assert.match(file, /success: false/, `${cse.plugin.id}: error path`);
    assert.match(file, /error_message: String\(err\)/, `${cse.plugin.id}: error message captured`);
    // The wrapped handler still rethrows (never swallows) errors
    assert.match(file, /throw err;/, `${cse.plugin.id}: rethrows after capture`);
    // Fixed v0 identity
    assert.ok(file.includes('= "mcp-server"'), `${cse.plugin.id}: fixed v0 identity`);

    // Flush handlers present only for the batching SDKs
    const hasSignalFlush = /process\.on\("SIGTERM"/.test(file);
    assert.equal(
      hasSignalFlush,
      cse.hasFlushHandlers,
      `${cse.plugin.id}: SIGTERM flush handler presence matches whether the SDK batches client-side`
    );
  });
}

test("mixpanel documents WHY it has no flush handler (SDK sends immediately)", () => {
  const file = vendoredFile(mixpanelPlugin);
  assert.match(
    file,
    /sends each event over HTTP immediately/,
    "the absence of a flush handler is documented in the vendored file, not silent"
  );
});
