// packages/cli/src/render/auth.ts
//
// OAuth 2.1 Resource Server support for --engine v2 --transport streamable-http
// (MCPFO-22). Per the MCP spec (2026-07-28, basic/authorization): the
// generated server acts ONLY as a Resource Server — it validates bearer
// tokens issued by an external Authorization Server (IdP), it never becomes
// an AS itself (no token issuance, no client registration, no consent UI).
// stdio servers MUST NOT implement this (spec: "SHOULD NOT... retrieve
// credentials from the environment instead") — this module is only wired
// into the streamable-http emit path in emit-server.ts.
//
// Design choice (decided Sep 3, 2026): a GENERIC, IdP-agnostic preset —
// issuer URL + JWKS URI (or JWKS URI derived from the issuer's OIDC discovery
// document) + expected audience — rather than vendor-specific presets
// (WorkOS/Auth0/Clerk). Works with any OAuth 2.1/OIDC-conformant IdP without
// klaridian maintaining per-vendor config shapes. Vendor-specific presets can
// be layered on top later as thin config wrappers if there's demand.
//
// Uses the SDK v2's own bearer-auth primitives (verifyBearerToken,
// bearerAuthChallengeResponse, oauthMetadataResponse,
// buildOAuthProtectedResourceMetadata, getOAuthProtectedResourceMetadataUrl)
// rather than hand-rolling HTTP semantics — klaridian only supplies the
// OAuthTokenVerifier (JWT signature/expiry/audience validation via `jose`'s
// createRemoteJWKSet, the standard zero-dependency JOSE library for Node).

export interface AuthOptions {
  /** OAuth 2.1 issuer URL of the external Authorization Server (IdP). */
  issuer: string;
  /**
   * JWKS URI to fetch signing keys from. When omitted, derived from the
   * issuer via OIDC discovery convention: `<issuer>/.well-known/jwks.json`
   * is NOT universal, so callers should prefer passing this explicitly;
   * emit-server.ts's CLI wiring resolves it from the issuer's discovery
   * document at generation time when possible (see generate.ts).
   */
  jwksUri: string;
  /**
   * Expected `aud` claim — the canonical URI of this MCP server (RFC 8707).
   * MUST match exactly what the AS was told to bind tokens to.
   */
  audience: string;
  /** Scopes required for every tool call. Empty = no scope enforcement beyond validity. */
  requiredScopes?: string[];
}

/**
 * Emits the vendored `src/auth.ts` file for the generated project: builds an
 * `OAuthTokenVerifier` backed by `jose`'s `createRemoteJWKSet` (validates
 * signature, expiry, issuer, and — critically, RFC 8707 — audience), and a
 * small set of helpers `emit-server.ts`'s HTTP entrypoint wires directly
 * into the `http.createServer` request handler.
 *
 * Vendored as literal source (not an klaridian-published npm dependency) —
 * same "plugin runtime code ships as readable source in the output" rule
 * already established for instrumentation plugins (PLAN.md section 7): an
 * MCP server's auth-checking code is exactly the kind of thing an operator
 * running it with real credentials next to an autonomous agent should be
 * able to read without trusting an opaque dependency.
 */
export function emitAuthModule(opts: AuthOptions): string {
  return `// src/auth.ts — generated by klaridian (MCPFO-22).
//
// OAuth 2.1 Resource Server wiring. This server validates bearer tokens
// issued by an external Authorization Server; it does NOT issue tokens,
// register clients, or show a consent UI. Per the MCP spec, the inbound
// token is NEVER forwarded to the upstream API (see src/index.ts) — if
// this server needs to call the upstream on the caller's behalf with
// separate credentials, that requires its own, distinct integration.
//
// Configuration (env vars, so the same build can point at different IdPs
// per deployment without a rebuild):
//   KLARIDIAN_OAUTH_ISSUER        (default: ${JSON.stringify(opts.issuer)})
//   KLARIDIAN_OAUTH_JWKS_URI      (default: ${JSON.stringify(opts.jwksUri)})
//   KLARIDIAN_OAUTH_AUDIENCE      (default: ${JSON.stringify(opts.audience)})
//   KLARIDIAN_OAUTH_REQUIRED_SCOPES (comma-separated, default: ${JSON.stringify((opts.requiredScopes ?? []).join(","))})

import { createRemoteJWKSet, jwtVerify, errors as joseErrors } from "jose";
import {
  verifyBearerToken,
  bearerAuthChallengeResponse,
  buildOAuthProtectedResourceMetadata,
  getOAuthProtectedResourceMetadataUrl,
  oauthMetadataResponse,
  OAuthError,
  OAuthErrorCode,
  type AuthInfo,
  type OAuthTokenVerifier,
  type OAuthMetadata,
} from "@modelcontextprotocol/server";
import { toWebRequest } from "@modelcontextprotocol/node";
import type { IncomingMessage, ServerResponse } from "node:http";

const issuer = process.env.KLARIDIAN_OAUTH_ISSUER || ${JSON.stringify(opts.issuer)};
const jwksUri = process.env.KLARIDIAN_OAUTH_JWKS_URI || ${JSON.stringify(opts.jwksUri)};
const audience = process.env.KLARIDIAN_OAUTH_AUDIENCE || ${JSON.stringify(opts.audience)};
const requiredScopes = (process.env.KLARIDIAN_OAUTH_REQUIRED_SCOPES ?? ${JSON.stringify((opts.requiredScopes ?? []).join(","))})
  .split(",")
  .map((s) => s.trim())
  .filter(Boolean);

const jwks = createRemoteJWKSet(new URL(jwksUri));

/**
 * Validates a JWT's signature (against the IdP's live JWKS), expiry, issuer,
 * and — the RFC 8707 requirement the MCP spec calls out explicitly — that
 * its \`aud\` claim includes this server's canonical resource URI. Any
 * failure throws OAuthError(InvalidToken), which the bearer-auth helpers
 * turn into a spec-shaped 401 challenge.
 */
const verifier: OAuthTokenVerifier = {
  async verifyAccessToken(token: string): Promise<AuthInfo> {
    try {
      const { payload } = await jwtVerify(token, jwks, { issuer, audience });
      const scopeClaim = typeof payload.scope === "string" ? payload.scope : "";
      const scopes = scopeClaim.split(" ").filter(Boolean);
      return {
        token,
        clientId: typeof payload.client_id === "string" ? payload.client_id : (payload.sub ?? "unknown"),
        scopes,
        expiresAt: payload.exp,
        resource: new URL(audience),
      };
    } catch (err) {
      if (err instanceof joseErrors.JWTExpired) {
        throw new OAuthError(OAuthErrorCode.InvalidToken, "Token expired");
      }
      if (err instanceof joseErrors.JWTClaimValidationFailed && err.claim === "aud") {
        // RFC 8707: a token not bound to this resource server MUST be rejected.
        throw new OAuthError(OAuthErrorCode.InvalidToken, "Token audience does not match this server");
      }
      throw new OAuthError(OAuthErrorCode.InvalidToken, "Token signature/claims invalid");
    }
  },
};

const resourceMetadataUrl = getOAuthProtectedResourceMetadataUrl(new URL(audience));

const oauthMetadata: OAuthMetadata = {
  issuer,
  authorization_endpoint: \`\${issuer}/authorize\`,
  token_endpoint: \`\${issuer}/token\`,
  response_types_supported: ["code"],
};

/**
 * Called once per HTTP request before the MCP handler. Serves the two
 * well-known OAuth discovery documents (PRM + AS metadata passthrough) when
 * the path matches; otherwise validates the Authorization header and either
 * returns a ready-to-send 401/403 Response or the verified AuthInfo to
 * attach to the request before handing off to the MCP handler.
 *
 * Deliberately does NOT call toWebRequest()/consume the request body for
 * every request — only the two well-known discovery paths need a full Request
 * object (they have no body), and toWebRequest() reads the IncomingMessage
 * stream, which would starve the MCP handler's own body parsing on every
 * other request. The well-known paths are recognized by a plain URL check
 * first, so a normal tools/call's body is never touched here.
 */
export async function authenticate(
  req: IncomingMessage,
  res: ServerResponse
): Promise<AuthInfo | "handled"> {
  const url = new URL(req.url ?? "/", \`http://\${req.headers.host ?? "localhost"}\`);
  if (url.pathname.startsWith("/.well-known/oauth-protected-resource") || url.pathname === "/.well-known/oauth-authorization-server") {
    const webRequest = await toWebRequest(req);
    const discovery = oauthMetadataResponse(webRequest, {
      oauthMetadata,
      resourceServerUrl: new URL(audience),
      scopesSupported: requiredScopes.length > 0 ? requiredScopes : undefined,
    });
    if (discovery) {
      await writeWebResponse(discovery, res);
      return "handled";
    }
  }

  try {
    const authInfo = await verifyBearerToken(req.headers.authorization, {
      verifier,
      requiredScopes,
      resourceMetadataUrl,
    });
    return authInfo;
  } catch (err) {
    const challenge = bearerAuthChallengeResponse(err, { requiredScopes, resourceMetadataUrl });
    await writeWebResponse(challenge, res);
    return "handled";
  }
}

async function writeWebResponse(response: Response, res: ServerResponse): Promise<void> {
  const headers: Record<string, string> = {};
  response.headers.forEach((value, key) => {
    headers[key] = value;
  });
  res.writeHead(response.status, headers);
  const body = response.body ? await response.arrayBuffer() : undefined;
  res.end(body ? Buffer.from(body) : undefined);
}
`;
}
