// packages/cli/src/render/instrument.ts
//
// Post-processes a server generated by openapi-mcp-generator to wire in an
// observability plugin (ARCHITECTURE.md section 16/18 — the pivot to using
// openapi-mcp-generator as the generation engine, focusing mcpforge's own
// code entirely on the instrumentation layer).
//
// openapi-mcp-generator dispatches EVERY tool call through a single
// `executeApiTool(toolName, definition, toolArgs, allSecuritySchemes)`
// function (see its src/utils/code-gen.ts generateCallToolHandler and
// src/generator/server-code.ts). This is a simpler injection point than
// mcpforge's own earlier per-tool-function generation (superseded, see
// section 15/17) — instrumentation only needs to wrap ONE call site, not
// one per tool, via a small textual patch rather than a full codemod.

import type { ObservabilityPlugin, ResolvedPluginConfig } from "../plugins/plugin.interface.js";

/** The exact call-site openapi-mcp-generator's generated code always contains. */
const CALL_SITE = "return await executeApiTool(toolName, toolDefinition, toolArgs ?? {}, securitySchemes);";

export class InstrumentationPatchError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "InstrumentationPatchError";
  }
}

/**
 * Rewrites the single `executeApiTool(...)` call site in generated server
 * source to route through the plugin's wrap function, and prepends the
 * plugin's import statement.
 *
 * Fails loudly (ARCHITECTURE.md section 7/8's rule, applied here too) if
 * the expected call site isn't found verbatim — rather than silently
 * producing an uninstrumented server, which would be a much worse failure
 * mode than refusing outright. openapi-mcp-generator's generated shape is
 * not a contract we control, so this needs to be re-verified whenever its
 * version is bumped (see ARCHITECTURE.md section 18 for the follow-up
 * this implies: pin the version, add a canary test).
 */
export function instrumentGeneratedServer(serverSource: string, plugin: ObservabilityPlugin): string {
  if (!serverSource.includes(CALL_SITE)) {
    throw new InstrumentationPatchError(
      `Could not find the expected executeApiTool call site in the generated server source. ` +
        `This likely means openapi-mcp-generator's generated code shape changed in a way mcpforge's ` +
        `instrumentation patch doesn't yet handle — check its version and update instrumentGeneratedServer() accordingly.`
    );
  }

  const wiring = plugin.getServerWiring();

  const instrumentedCallSite = `return await ${wiring.wrapFunctionName}(toolName, () => executeApiTool(toolName, toolDefinition, toolArgs ?? {}, securitySchemes))();`;

  const withCallSitePatched = serverSource.replace(CALL_SITE, instrumentedCallSite);

  // Insert the plugin's import right after the last existing top-of-file
  // import statement, so it participates in normal ESM import ordering
  // rather than being appended awkwardly at the end of the import block.
  const importInsertionMarker = "import { z, ZodError } from 'zod';";
  if (!withCallSitePatched.includes(importInsertionMarker)) {
    throw new InstrumentationPatchError(
      `Could not find the expected zod import marker to insert the plugin import after. ` +
        `openapi-mcp-generator's import ordering may have changed — update instrumentGeneratedServer() accordingly.`
    );
  }

  return withCallSitePatched.replace(
    importInsertionMarker,
    `${importInsertionMarker}\n${wiring.importStatement}`
  );
}

/**
 * Writes the plugin's own contributed files (e.g. the vendored OTel
 * instrumentation module) into the generated project, and returns the npm
 * dependencies the project's package.json needs to add.
 */
export function getPluginProjectAdditions(
  plugin: ObservabilityPlugin,
  config: ResolvedPluginConfig
): { files: { path: string; content: string }[]; dependencies: Record<string, string> } {
  const contributions = plugin.getTemplateContributions(config);
  const files = contributions.map((c) => ({
    path: c.path,
    content: typeof c.content === "function" ? c.content(config) : c.content,
  }));
  return { files, dependencies: plugin.getDependencies() };
}
