// packages/cli/src/render/render-project.ts
//
// Orchestrates writing a complete, standalone MCP server project to disk:
// package.json, tsconfig.json, README.md, and src/index.ts (from
// generate-server-code.ts). No plugins/instrumentation yet — that's the
// next build-order step per ARCHITECTURE.md section 9.

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import type { MappingResult } from "../openapi/types.js";
import { generateServerSource } from "./generate-server-code.js";
import type { ObservabilityPlugin, ResolvedPluginConfig } from "../plugins/plugin.interface.js";

export interface RenderOptions {
  outputDir: string;
  serverName: string;
  version?: string;
  /** At most one plugin is supported in v0 (see generate-server-code.ts). */
  plugin?: ObservabilityPlugin;
  pluginConfig?: ResolvedPluginConfig;
}

function generatePackageJson(options: RenderOptions): string {
  return JSON.stringify(
    {
      name: options.serverName,
      version: options.version ?? "0.0.1",
      private: true,
      type: "module",
      description: `MCP server generated by mcpforge from an OpenAPI spec.`,
      scripts: {
        build: "tsc -p tsconfig.json",
        start: "node dist/index.js",
      },
      dependencies: {
        "@modelcontextprotocol/sdk": "^1.0.0",
        ...(options.plugin ? options.plugin.getDependencies() : {}),
      },
      devDependencies: {
        typescript: "^5.7.3",
        "@types/node": "^22.10.5",
      },
    },
    null,
    2
  );
}

function generateTsconfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2022",
        module: "NodeNext",
        moduleResolution: "NodeNext",
        outDir: "dist",
        rootDir: "src",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
      },
      include: ["src/**/*.ts"],
    },
    null,
    2
  );
}

function generateReadme(options: RenderOptions, mapping: MappingResult): string {
  const toolList = mapping.tools.map((t) => `- \`${t.name}\` — ${t.description}`).join("\n");
  const needsBaseUrl = !mapping.baseUrl || !/^https?:\/\//.test(mapping.baseUrl);

  return `# ${options.serverName}

> Generated by [mcpforge](https://github.com/ricardocvasconcelos/mcpforge) from an OpenAPI spec. Do not hand-edit \`src/index.ts\` — regenerate it instead.

## Setup

\`\`\`bash
npm install
npm run build
\`\`\`

${
  needsBaseUrl
    ? `## Required configuration

The source OpenAPI spec declared a server URL ("${mapping.baseUrl ?? "none"}") that mcpforge could not treat as a complete host. Set the base URL to call before running:

\`\`\`bash
export MCPFORGE_BASE_URL=https://api.example.com
\`\`\`
`
    : `## Configuration

By default this server calls \`${mapping.baseUrl}\`. Override with the \`MCPFORGE_BASE_URL\` environment variable if needed.
`
}
${
  mapping.auth
    ? `## Authentication

This API requires ${
        mapping.auth.type === "http-bearer"
          ? "an HTTP Bearer token"
          : `an API key ("${mapping.auth.paramName}", sent via ${mapping.auth.in})`
      }. Set it before running:

\`\`\`bash
export MCPFORGE_AUTH_TOKEN=your-credential-here
\`\`\`

The generated server will refuse to start without this variable set.
`
    : ""
}

## Running

\`\`\`bash
npm start
\`\`\`

This is a stdio-transport MCP server — connect it from an MCP client (Claude Desktop, an agent) by pointing it at \`node dist/index.js\` in this directory.

## Tools

${toolList}

${
  mapping.warnings.length > 0
    ? `## Generation warnings

The generator produced ${mapping.warnings.length} warning(s) while mapping the OpenAPI spec (non-fatal — these tools were still generated, but double-check them):

${mapping.warnings.map((w) => `- **${w.method.toUpperCase()} ${w.path}**: ${w.message}`).join("\n")}
`
    : ""
}
`;
}

/**
 * Renders a complete MCP server project to `options.outputDir`.
 * Assumes `mapping.errors` is empty — the caller (CLI command) is
 * responsible for surfacing errors and refusing to generate, per
 * ARCHITECTURE.md section 8 ("fail loudly, don't guess").
 */
export async function renderProject(mapping: MappingResult, options: RenderOptions): Promise<void> {
  if (mapping.errors.length > 0) {
    throw new Error(
      `renderProject called with ${mapping.errors.length} unresolved mapping error(s) — refusing to generate. ` +
        `Fix the OpenAPI spec or filter out failing operations before rendering.`
    );
  }

  await mkdir(path.join(options.outputDir, "src"), { recursive: true });

  await writeFile(path.join(options.outputDir, "package.json"), generatePackageJson(options), "utf-8");
  await writeFile(path.join(options.outputDir, "tsconfig.json"), generateTsconfig(), "utf-8");
  await writeFile(path.join(options.outputDir, "README.md"), generateReadme(options, mapping), "utf-8");
  await writeFile(
    path.join(options.outputDir, "src", "index.ts"),
    generateServerSource(mapping.tools, {
      serverName: options.serverName,
      version: options.version ?? "0.0.1",
      plugins: options.plugin ? [options.plugin] : [],
      auth: mapping.auth,
    }),
    "utf-8"
  );

  if (options.plugin) {
    const config = options.pluginConfig ?? {};
    const contributions = options.plugin.getTemplateContributions(config);
    for (const contribution of contributions) {
      const filePath = path.join(options.outputDir, contribution.path);
      await mkdir(path.dirname(filePath), { recursive: true });
      const content = typeof contribution.content === "function" ? contribution.content(config) : contribution.content;
      await writeFile(filePath, content, "utf-8");
    }
  }
}
