// packages/cli/src/emit/conformance/python.ts
//
// MCPFO-60.3 — the Python conformance adapter.
//
// Unlike the TypeScript SDK v2 (natively conformant, so its adapter emits ""),
// the official Python SDK's low-level `Server` gives NONE of the conformance
// contract for free — spike 059 (ARCHITECTURE.md section 60.1) found a naive
// Python handler produced a non-spec `code: 0` for an unknown tool, and the
// low-level Server does no argument validation at all. So THIS adapter injects
// real server code: a vendored `conformance.py` module the generated server
// imports and routes every unknown-tool / invalid-arguments / tool-execution
// failure through.
//
// Verified against the real SDK (mcp==2.1.1, see the emit-python-e2e test):
//   - unknownTool → raise MCPError(INVALID_PARAMS). The SDK's
//     `handler_exception_to_error_data` maps a raised MCPError to its own
//     ErrorData, so the wire response is a JSON-RPC protocol error -32602 —
//     NOT the `code: 0` a bare `raise ValueError(...)` produces. This is the
//     exact gap the spike surfaced.
//   - invalidArguments → validate the arguments against the tool's JSON Schema
//     with the `jsonschema` library (already a transitive dep of `mcp`) and,
//     on failure, RETURN a CallToolResult(isError=True) — a tool-error result,
//     NOT a raised protocol error — per the MCP two-tier model (section 28 /
//     60.1). Maintainer decision (Sep 6, 2026): validate the IR's JSON Schema
//     directly rather than generating a Pydantic model per tool — no lossy
//     schema→model conversion, and it checks the exact same schema the TS side
//     carries. This deviates from the ticket's literal "→ Pydantic" wording;
//     recorded as a deliberate choice, see ARCHITECTURE.md section 61.
//   - toolExecutionError → the tool's own proxy returns isError=True on an
//     upstream failure, surfaced as a tool-error result.

import {
  CONFORMANCE_CONTRACT,
  JSONRPC_INVALID_PARAMS,
  type ConformanceAdapter,
  type ConformanceContract,
} from "./contract.js";

/**
 * The vendored `conformance.py` module. Human-readable source (section 7's
 * vendored-file rule), not an opaque runtime dependency. server.py imports
 * `raise_unknown_tool`, `validate_arguments`, and `tool_error` from it.
 */
function emitConformanceModule(): string {
  return `# GENERATED by klaridian (Python conformance adapter) — vendored, do not edit.
#
# Guarantees the spec-mandated MCP error surfaces the low-level Python SDK does
# NOT provide for free (spike 059, ARCHITECTURE.md sections 60.1/61):
#   - unknown tool        -> JSON-RPC protocol error -32602 (raise MCPError)
#   - invalid arguments   -> tool-error result (isError=True), NOT a protocol
#                            error, per the MCP two-tier model
#   - tool execution error-> tool-error result (isError=True)
import json

import jsonschema
from mcp.shared.exceptions import MCPError
from mcp import types

# JSON-RPC 2.0 "invalid params" — what an unknown-tool call must surface as at
# the protocol level in MCP.
INVALID_PARAMS = ${JSONRPC_INVALID_PARAMS}


def raise_unknown_tool(name: str) -> None:
    """A tools/call naming a tool that isn't registered is a PROTOCOL error.

    Raising MCPError (not a bare Exception) is load-bearing: the SDK maps a
    raised MCPError to its own ErrorData, so the wire response is -32602. A
    bare \`raise ValueError(...)\` instead yields a generic code:0 — the exact
    non-conformance spike 059 found.
    """
    raise MCPError(INVALID_PARAMS, f"Unknown tool: {name}")


def tool_error(message: str) -> types.CallToolResult:
    """Build a tool-error RESULT (isError=True). Used for invalid arguments and
    upstream/tool-execution failures — anything that happens while running the
    tool, which the MCP two-tier model surfaces as a result the model can see
    and react to, not a protocol error."""
    return types.CallToolResult(
        content=[types.TextContent(type="text", text=message)],
        is_error=True,
    )


def validate_arguments(schema: dict, arguments: dict) -> types.CallToolResult | None:
    """Validate call arguments against the tool's JSON Schema.

    Returns a tool-error CallToolResult on failure (per the two-tier model), or
    None when the arguments are valid. Validates the IR's JSON Schema directly
    (the same schema the TypeScript target carries) rather than converting to a
    Pydantic model — no lossy schema->model round-trip. See ARCHITECTURE.md
    section 61.
    """
    try:
        jsonschema.validate(instance=arguments, schema=schema)
    except jsonschema.ValidationError as exc:
        return tool_error(f"Input validation error: {exc.message}")
    return None
`;
}

export const pythonConformanceAdapter: ConformanceAdapter = {
  language: "python",
  contract: CONFORMANCE_CONTRACT,
  emitServerContributions(): string {
    // Unlike TypeScript, Python is NOT natively conformant — this returns real
    // vendored server code the emitter writes to conformance.py.
    return emitConformanceModule();
  },
  describeCoverage(): string {
    return [
      "unknownTool: injected protocol error — conformance.py's",
      "  raise_unknown_tool() raises MCPError(INVALID_PARAMS); the SDK maps it",
      "  to a -32602 wire error (a bare exception would yield code:0).",
      "invalidArguments: injected tool-error — conformance.py's",
      "  validate_arguments() checks the tool's JSON Schema with jsonschema and",
      "  returns CallToolResult(isError=True) on failure, per the two-tier model.",
      "toolExecutionError: injected tool-error — each tool proxy returns",
      "  isError=True on an upstream HTTP failure.",
    ].join("\n");
  },
};

/** Re-exported for callers that only need the contract shape. */
export type { ConformanceContract };
