// packages/cli/src/plugins/amplitude/amplitude.plugin.ts
//
// Product-observability plugin #2 (ARCHITECTURE.md section 26 — multiple
// product-analytics providers, since unlike OTel/OTLP on the engineering
// side, there is no analogous open standard/wire-protocol on the product
// side that would let one plugin fan out to every backend). Mirrors
// posthog.plugin.ts's shape closely: same ObservabilityPlugin interface,
// same vendored-file-in-src/instrumentation/ pattern, same one-event-per-
// tool-call scope.
//
// stdio-safety note (checked directly against the installed package, not
// assumed — see ARCHITECTURE.md section 26): @amplitude/analytics-node's
// internal Logger defaults to LogLevel.None, so it never calls
// console.log/console.debug unless the user explicitly opts into a more
// verbose logLevel in config — which this plugin does not do. No
// ConsoleSpanExporter-style landmine here.

import type {
  ObservabilityPlugin,
  PluginConfigField,
  ResolvedPluginConfig,
  TemplateContribution,
} from "../plugin.interface.js";

const CONFIG_SCHEMA: PluginConfigField[] = [
  {
    key: "serverZone",
    prompt: "Amplitude server zone (US or EU)",
    default: "US",
    required: true,
  },
];

function generateInstrumentationFile(config: ResolvedPluginConfig): string {
  return `// GENERATED by klaridian (amplitude plugin) — vendored instrumentation helper.
// Captures one "mcp tool called" event per tool call: name, duration,
// success/error. @amplitude/analytics-node's own Logger defaults to
// LogLevel.None (verified directly against the installed package — see
// ARCHITECTURE.md section 26) — never writes to stdout unless a caller
// explicitly raises the log level, which this file does not do. Safe
// alongside stdio MCP transport for the same reason the OTel/PostHog
// plugins are (see spikes/001-otel-mechanic/FINDINGS.md for why that distinction matters).

import { init, track, flush } from "@amplitude/analytics-node";

const API_KEY = process.env.AMPLITUDE_API_KEY;
if (!API_KEY) {
  console.error(
    "Missing required environment variable AMPLITUDE_API_KEY. " +
      "Set it to your Amplitude project API key to enable product observability, " +
      "or remove the amplitude plugin at generation time if you don't want it."
  );
  process.exit(1);
}

const SERVER_ZONE = (process.env.AMPLITUDE_SERVER_ZONE || ${JSON.stringify(config.serverZone)}) as "US" | "EU";

init(API_KEY, { serverZone: SERVER_ZONE });

// Flush on exit — the SDK batches events internally (flushQueueSize/
// flushIntervalMillis), so an unflushed batch is lost on process exit
// otherwise (same class of bug as OTel's BatchSpanProcessor finding in
// spikes/001-otel-mechanic/FINDINGS.md, different SDK).
process.on("SIGINT", () => flush().promise.finally(() => process.exit(0)));
process.on("SIGTERM", () => flush().promise.finally(() => process.exit(0)));

/**
 * Wraps an MCP tool handler to capture an Amplitude product-analytics
 * event per call. Every generated tool is wired through this — no
 * per-tool custom instrumentation code needed, mirroring the OTel/PostHog
 * plugins' wrapTool functions.
 */
export function wrapAmplitudeTool<T extends (args: any) => Promise<unknown>>(toolName: string, handler: T): T {
  return (async (args: any) => {
    const startedAt = Date.now();
    // A fixed deviceId is a deliberate v0 simplification, mirroring the
    // PostHog plugin's fixed distinctId: a generated stdio MCP server has
    // no notion of an end-user identity (the caller is an MCP client, not
    // a logged-in human) — every event is attributed to the server
    // itself. Revisit if/when per-caller identity becomes available.
    const deviceId = "mcp-server";
    try {
      const result = await handler(args);
      track(
        "mcp tool called",
        { tool_name: toolName, duration_ms: Date.now() - startedAt, success: true },
        { device_id: deviceId }
      );
      return result;
    } catch (err) {
      track(
        "mcp tool called",
        {
          tool_name: toolName,
          duration_ms: Date.now() - startedAt,
          success: false,
          error_message: String(err),
        },
        { device_id: deviceId }
      );
      throw err;
    }
  }) as T;
}
`;
}

export const amplitudePlugin: ObservabilityPlugin = {
  id: "amplitude",
  name: "Amplitude (product observability)",
  configSchema: CONFIG_SCHEMA,

  getTemplateContributions(config: ResolvedPluginConfig): TemplateContribution[] {
    return [
      {
        path: "src/instrumentation/amplitude.ts",
        content: generateInstrumentationFile(config),
      },
    ];
  },

  getDependencies(): Record<string, string> {
    return {
      "@amplitude/analytics-node": "^1.5.0",
    };
  },

  getServerWiring() {
    return {
      importStatement: `import { wrapAmplitudeTool } from "./instrumentation/amplitude.js";`,
      wrapFunctionName: "wrapAmplitudeTool",
    };
  },
};
