// packages/cli/src/plugins/shared/product-analytics-python-template.ts
//
// The Python peer of product-analytics-template.ts (MCPFO-60.3). Assembles a
// complete, self-contained vendored `instrumentation/<id>.py` for the three
// product-analytics plugins (posthog, amplitude, mixpanel) from each provider's
// SDK-specific pieces — same split as the TypeScript template: only the
// provider's import/init/flush/capture lines differ, the wrap skeleton and the
// missing-credential guard are shared.
//
// Wrap shape is Python's SHARED-DISPATCH idiom (MCPFO-60.2): the exported
// wrap_dispatch(dispatch) wraps the server's single _dispatch(tool_name,
// arguments) once, so every tool call is captured — not per-tool like TS.
//
// As in TypeScript, this does NOT collapse the per-plugin vendored FILE: each
// plugin still emits its own readable, auditable module (section 7). Only
// klaridian's own generator code is deduplicated.

/** The provider-specific pieces each Python analytics plugin supplies. */
export interface PythonProductAnalyticsTemplate {
  /** Plugin id, e.g. "posthog" — used only in the generated header comment. */
  pluginId: string;
  /** stdio-safety note lines (provider-specific), each a bare line (the caller
   *  adds the `# ` prefix), mirroring the TS template. */
  stdioSafetyLines: string[];
  /** Provider SDK import line(s), e.g. `from posthog import Posthog`. */
  importStatement: string;
  /** Env var holding the provider credential, e.g. "POSTHOG_API_KEY". */
  credentialEnvVar: string;
  /** Human phrase for the missing-credential error, e.g. "your PostHog project API key". */
  credentialDescription: string;
  /** Local name the guard binds the credential to, e.g. "API_KEY" / "TOKEN". */
  credentialConstName: string;
  /** Provider client init statements (module level; may reference the
   *  credential const and other os.environ config with a baked-in default). */
  initStatements: string;
  /** Optional atexit flush registration, for SDKs that batch client-side
   *  (posthog, amplitude). Omit for send-immediately SDKs (mixpanel). */
  flushHandlers?: string;
  /** Local const name for the fixed v0 identity, e.g. "distinct_id"/"device_id". */
  identityConstName: string;
  /**
   * Given the identity const name and whether the call succeeded, returns the
   * capture statement emitted inside the try/except. `success` false paths add
   * an error_message. Provider capture APIs differ enough to keep this a
   * callback rather than more parameters (mirrors the TS template).
   */
  captureStatement: (opts: { identityConst: string; success: boolean }) => string;
}

/**
 * Assembles a complete Python `instrumentation/<id>.py`. The returned string is
 * written to the generated Python project by the plugin's python contribution.
 */
export function buildPythonProductAnalyticsInstrumentationFile(
  t: PythonProductAnalyticsTemplate
): string {
  const flushBlock = t.flushHandlers ? `\n${t.flushHandlers}\n` : "";
  const stdioSafety = t.stdioSafetyLines.map((l) => `# ${l}`).join("\n");

  return `# GENERATED by klaridian (${t.pluginId} plugin, Python target) — vendored instrumentation helper.
# Captures one "mcp tool called" event per tool call: name, duration,
# success/error. Wraps the server's shared _dispatch once (MCPFO-60.2).
${stdioSafety}
import os
import sys
import time

${t.importStatement}

${t.credentialConstName} = os.environ.get("${t.credentialEnvVar}")
if not ${t.credentialConstName}:
    print(
        "Missing required environment variable ${t.credentialEnvVar}. "
        "Set it to ${t.credentialDescription} to enable product observability, "
        "or remove the ${t.pluginId} plugin at generation time if you don't want it.",
        file=sys.stderr,
    )
    sys.exit(1)

${t.initStatements}
${flushBlock}

def wrap_dispatch(dispatch):
    """Wrap the server's shared _dispatch(tool_name, arguments) to capture a
    ${t.pluginId} product-analytics event per call. Every tool call flows through
    _dispatch, so one wrap covers them all — the Python peer of the TS per-tool
    wrap."""

    async def wrapped(tool_name, arguments):
        started_at = time.monotonic()
        # A fixed identity is a deliberate v0 simplification: a generated MCP
        # server has no end-user identity (the caller is an MCP client, not a
        # logged-in human) — every event is attributed to the server itself.
        ${t.identityConstName} = "mcp-server"
        try:
            result = await dispatch(tool_name, arguments)
            ${t.captureStatement({ identityConst: t.identityConstName, success: true })}
            return result
        except Exception as err:  # noqa: BLE001
            ${t.captureStatement({ identityConst: t.identityConstName, success: false })}
            raise

    return wrapped
`;
}
