// packages/cli/src/plugins/shared/product-analytics-template.ts
//
// Shared generator for the three product-analytics plugins' vendored
// instrumentation files (posthog, amplitude, mixpanel). Extracted during the
// Sep 6 2026 repo audit (ARCHITECTURE.md section 58): the three plugins'
// generateInstrumentationFile() functions were ~90% identical boilerplate
// (header comment, missing-env-var guard, the wrapTool try/catch/throw
// skeleton, the fixed-identity v0 comment) with only the provider SDK's
// import/init/capture/flush lines genuinely differing per provider.
//
// IMPORTANT — this does NOT collapse the per-plugin vendored FILES. Each
// plugin still contributes its own complete, self-contained, human-readable
// `src/instrumentation/<id>.ts` into the generated project (PLAN.md section 7's
// auditability rule: plugin runtime code ships as vendored source, never an
// opaque dependency). What's deduplicated is klaridian's own *generator* code
// that assembles that file — an implementation detail of the CLI, not the
// emitted artifact. The output is byte-for-byte a normal, readable file a user
// can audit; it just isn't hand-assembled three times inside klaridian.

/** The provider-specific pieces each analytics plugin supplies. */
export interface ProductAnalyticsTemplate {
  /** Plugin id, e.g. "posthog" — only used in the generated header comment. */
  pluginId: string;
  /**
   * The stdio-safety paragraph, provider-specific (each SDK has a different
   * reason it's safe alongside stdio MCP transport — see ARCHITECTURE.md
   * section 26). Emitted verbatim into the generated file's header comment,
   * one `// ` per line already applied by the caller's array entries.
   */
  stdioSafetyLines: string[];
  /** The provider SDK import line(s), e.g. `import { PostHog } from "posthog-node";` */
  importStatement: string;
  /** Env var holding the provider credential, e.g. "POSTHOG_API_KEY". */
  credentialEnvVar: string;
  /** Human phrase for the missing-credential error, e.g. "your PostHog project API key". */
  credentialDescription: string;
  /**
   * Local const name the guard binds the credential to, e.g. "API_KEY" or
   * "TOKEN" — so `initStatements` can reference it.
   */
  credentialConstName: string;
  /**
   * Provider client init statements (may reference the credential const bound
   * by the guard, and other `process.env.*` config with a baked-in default).
   */
  initStatements: string;
  /**
   * Optional SIGINT/SIGTERM flush handlers, for SDKs that batch client-side
   * (posthog, amplitude). Omit for SDKs that send each event immediately
   * (mixpanel) — a real per-SDK difference, not an oversight.
   */
  flushHandlers?: string;
  /** Exported wrap-function name, e.g. "wrapPostHogTool". */
  wrapFunctionName: string;
  /** Local const name for the fixed v0 identity, e.g. "distinctId" or "deviceId". */
  identityConstName: string;
  /**
   * Given the local identity const name and whether the call succeeded,
   * returns the capture statement to emit inside the try/catch. `success`
   * false paths add `error_message: String(err)`. Provider capture APIs
   * differ enough (posthog.capture({...}) vs track(name, props, {device_id})
   * vs mixpanel.track(name, {distinct_id,...})) that this stays a callback
   * rather than more parameters.
   */
  captureStatement: (opts: { identityConst: string; success: boolean }) => string;
}

/**
 * Assembles a complete, self-contained vendored instrumentation file from a
 * provider's template pieces. The returned string is what gets written to the
 * generated project's `src/instrumentation/<id>.ts`.
 */
export function buildProductAnalyticsInstrumentationFile(t: ProductAnalyticsTemplate): string {
  const flushBlock = t.flushHandlers ? `\n${t.flushHandlers}\n` : "";
  const stdioSafety = t.stdioSafetyLines.map((l) => `// ${l}`).join("\n");

  return `// GENERATED by klaridian (${t.pluginId} plugin) — vendored instrumentation helper.
// Captures one "mcp tool called" event per tool call: name, duration,
// success/error.
${stdioSafety}

${t.importStatement}

const ${t.credentialConstName} = process.env.${t.credentialEnvVar};
if (!${t.credentialConstName}) {
  console.error(
    "Missing required environment variable ${t.credentialEnvVar}. " +
      "Set it to ${t.credentialDescription} to enable product observability, " +
      "or remove the ${t.pluginId} plugin at generation time if you don't want it."
  );
  process.exit(1);
}

${t.initStatements}
${flushBlock}
/**
 * Wraps an MCP tool handler to capture a ${t.pluginId} product-analytics event
 * per call. Every generated tool is wired through this — no per-tool custom
 * instrumentation code needed, mirroring the OTel plugin's wrapTool.
 */
export function ${t.wrapFunctionName}<T extends (args: any) => Promise<unknown>>(toolName: string, handler: T): T {
  return (async (args: any) => {
    const startedAt = Date.now();
    // A fixed identity is a deliberate v0 simplification: a generated stdio
    // MCP server has no notion of an end-user identity (the caller is an MCP
    // client, not a logged-in human) — every event is attributed to the
    // server itself. Revisit if/when per-caller identity becomes available.
    const ${t.identityConstName} = "mcp-server";
    try {
      const result = await handler(args);
      ${t.captureStatement({ identityConst: t.identityConstName, success: true })}
      return result;
    } catch (err) {
      ${t.captureStatement({ identityConst: t.identityConstName, success: false })}
      throw err;
    }
  }) as T;
}
`;
}
