"""
spikes/059-python-emit-target/emit_python.py

Throwaway Python emitter for klaridian's MCP tool IR. Reads the SAME tool-data
shape klaridian's TS emitter consumes (openapi-mcp-generator's
getToolsFromOpenApi output — see spikes/059-python-emit-target/petstore-tools.json,
captured verbatim from the real klaridian dependency), and emits a standalone
Python MCP server project using the official Python MCP SDK (mcp==2.1.1) +
httpx, mirroring what packages/cli/src/emit/emit-server.ts + emit-tool.ts do
for TypeScript.

Goal: find out what klaridian's IR (the JSON tool-data contract) does and does
NOT carry cleanly into a second-language emitter, to inform ARCHITECTURE.md.

This is a SPIKE. Do not wire into the real CLI. Throwaway code.
"""
import json
import re
import sys
from pathlib import Path


def to_snake(name: str) -> str:
    s1 = re.sub(r"(.)([A-Z][a-z]+)", r"\1_\2", name)
    s2 = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", s1)
    return s2.lower()


def json_schema_to_pydantic_hint(schema: dict) -> str:
    """Very small JSON-Schema -> Python type-hint mapper (spike-grade, not a
    full port of json-schema-to-zod)."""
    t = schema.get("type")
    if t == "integer":
        return "int"
    if t == "number":
        return "float"
    if t == "boolean":
        return "bool"
    if t == "array":
        return "list"
    if t == "object":
        return "dict"
    return "str"  # default, incl. "string" and untyped/enum


def emit_tool_module(tool: dict) -> tuple[str, str]:
    """Returns (module_filename, module_source) for one tool."""
    name = tool["name"]
    snake = to_snake(name)
    input_schema = tool.get("inputSchema", {"type": "object", "properties": {}})
    params = tool.get("executionParameters", [])
    path_params = [p for p in params if p["in"] == "path"]
    query_params = [p for p in params if p["in"] == "query"]
    header_params = [p for p in params if p["in"] == "header"]
    has_body = bool(tool.get("requestBodyContentType"))
    method = (tool.get("method") or "get").upper()
    path_template = tool["pathTemplate"]

    lines = []
    lines.append("import os")
    lines.append("import httpx")
    lines.append("")
    lines.append(f'NAME = "{name}"')
    lines.append(f'INPUT_SCHEMA = {json.dumps(input_schema)}')
    lines.append("")
    lines.append("async def call(arguments: dict) -> dict:")
    lines.append('    base = os.environ.get("KLARIDIAN_BASE_URL")')
    lines.append('    if not base:')
    lines.append('        raise RuntimeError("KLARIDIAN_BASE_URL is not set")')
    lines.append(f'    path = {json.dumps(path_template)}')
    for p in path_params:
        lines.append(
            f'    path = path.replace("{{{p["name"]}}}", str(arguments.get("{p["name"]}")))'
        )
    lines.append("    query = {}")
    for p in query_params:
        lines.append(
            f'    if arguments.get("{p["name"]}") is not None:'
        )
        lines.append(f'        query["{p["name"]}"] = arguments.get("{p["name"]}")')
    lines.append("    headers = {}")
    for p in header_params:
        lines.append(
            f'    if arguments.get("{p["name"]}") is not None:'
        )
        lines.append(f'        headers["{p["name"]}"] = str(arguments.get("{p["name"]}"))')
    if has_body:
        lines.append('    body = arguments.get("requestBody")')
    else:
        lines.append("    body = None")
    lines.append(f'    async with httpx.AsyncClient(base_url=base) as client:')
    lines.append(
        f'        resp = await client.request({json.dumps(method)}, path, params=query, headers=headers, json=body)'
    )
    lines.append("        resp.raise_for_status()")
    lines.append('        content_type = resp.headers.get("content-type", "")')
    lines.append('        if "application/json" in content_type:')
    lines.append("            return resp.json()")
    lines.append("        return {\"text\": resp.text}")
    lines.append("")
    return f"tool_{snake}.py", "\n".join(lines)


SERVER_TEMPLATE = '''"""Generated by klaridian Python emit spike (059). Throwaway — do not ship."""
import asyncio
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))

from mcp import types
from mcp.server.lowlevel import Server
from mcp.server.lowlevel.server import NotificationOptions
from mcp.server.stdio import stdio_server

{tool_imports}

TOOLS = [
{tool_registry}
]

TOOL_MAP = {{t["module"].NAME: t for t in TOOLS}}


def annotations_for_method(method: str) -> types.ToolAnnotations:
    m = (method or "get").lower()
    read_only = m in ("get", "head")
    idempotent = m in ("get", "head", "put", "delete")
    destructive = m in ("delete", "put")
    return types.ToolAnnotations(
        read_only_hint=read_only,
        idempotent_hint=idempotent,
        destructive_hint=destructive,
        open_world_hint=True,
    )


async def on_list_tools(ctx, params):
    tools = []
    for entry in TOOLS:
        mod = entry["module"]
        tools.append(
            types.Tool(
                name=mod.NAME,
                title=entry["title"],
                description=(mod.__doc__ or ""),
                input_schema=mod.INPUT_SCHEMA,
                annotations=annotations_for_method(entry["method"]),
            )
        )
    return types.ListToolsResult(tools=tools)


async def on_call_tool(ctx, params):
    entry = TOOL_MAP.get(params.name)
    if entry is None:
        raise ValueError(f"Unknown tool: {{params.name}}")
    try:
        result = await entry["module"].call(params.arguments or {{}})
        return types.CallToolResult(
            content=[types.TextContent(type="text", text=json.dumps(result))],
        )
    except Exception as exc:  # noqa: BLE001 - proxy failures surface as tool errors
        return types.CallToolResult(
            content=[types.TextContent(type="text", text=str(exc))],
            is_error=True,
        )


async def main():
    server = Server(
        "{server_name}",
        version="0.0.1",
        on_list_tools=on_list_tools,
        on_call_tool=on_call_tool,
    )
    init_options = server.create_initialization_options(NotificationOptions())
    async with stdio_server() as (read_stream, write_stream):
        await server.run(read_stream, write_stream, init_options)


if __name__ == "__main__":
    asyncio.run(main())
'''


def emit_server_project(tools: list[dict], server_name: str, out_dir: Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    tool_imports = []
    tool_registry_lines = []
    for tool in tools:
        filename, source = emit_tool_module(tool)
        (out_dir / filename).write_text(source)
        modname = filename[:-3]
        title = tool.get("description") or tool["name"]
        tool_imports.append(f"import {modname}")
        tool_registry_lines.append(
            f'    {{"module": {modname}, "title": {json.dumps(title)}, "method": {json.dumps(tool.get("method","get"))}}},'
        )

    server_src = SERVER_TEMPLATE.format(
        tool_imports="\n".join(tool_imports),
        tool_registry="\n".join(tool_registry_lines),
        server_name=server_name,
    )
    (out_dir / "server.py").write_text(server_src)
    (out_dir / "requirements.txt").write_text("mcp==2.1.1\nhttpx>=0.27\n")


if __name__ == "__main__":
    tools_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path(__file__).parent / "petstore-tools.json"
    out = Path(sys.argv[2]) if len(sys.argv) > 2 else Path(__file__).parent / "out"
    tools = json.loads(tools_path.read_text())
    emit_server_project(tools, "petstore-py-spike", out)
    print(f"Emitted {len(tools)} tools to {out}")
